### ISSUE TITLE
OSError

### ISSUE THREAD

**Issue by naweiss** [Gallopsled/pwntools#1079]
Trying to run 32bit ELF on 64-bit Ubuntu 14.04 gives the following error:
```
>>>from pwn import *
>>> context.update(arch='i386',bits='32')
>>> p = process('./prog')
[x] Starting local process './prog'
[-] Starting local process './prog': Failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/naweiss/.local/lib/python2.7/site-packages/pwnlib/tubes/process.py", line 324, in __init__
    preexec_fn = self.__preexec_fn)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
_**Note:**_ I suspect the ELF is missing some library but the `OSError `doesn't specify which.

**Comment by zachriggle** [comment]
Can you run “prog” outside of pwntools? I expect you’re missing libraries
for it.

**Comment by naweiss** [comment]
I can't, because it's 32bit.
As I said, I believe it missing libraries, but why the `OSError` doesn't specify their names?
