### ISSUE TITLE
pwntools import error in wing ide 

### ISSUE THREAD

**Issue by najeex** [Gallopsled/pwntools#1110]
I am first-time use pwntools. i used wing ide (but out of wing ide all is fine ). and facing import error in the python shell. 
this is how I import in wing ide
```
from pwn import *
#log.info("hello")
```
error in python shell in wing ide 

```
from pwnlib import *
Traceback (most recent call last):
  Python Shell, prompt 11, line 1
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/__init__.py", line 43, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/args.py", line 61, in <module>
    from pwnlib import term
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/term/__init__.py", line 5, in <module>
    from pwnlib.term import completer
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/term/completer.py", line 6, in <module>
    from pwnlib.term import readline
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/term/readline.py", line 5, in <module>
    from pwnlib.term import keyconsts as kc
ImportError: cannot import name keyconsts
```
how to fix this. one more think for installing python packages i use **conda**. except for pwntools

**Comment by zachriggle** [comment]
This is an issue with your IDE, no idea dude.  I expect your installation is b0rked or your IDE does something weird.

Double-check that `pwnlib/term/keyconsts.py` actually exists.

**Comment by faraazahmad** [comment]
I have a similar problem
```
➜  ~ py     
Python 3.6.5 |Anaconda, Inc.| (default, Apr 29 2018, 16:14:56) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwntools import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'pwntools'
>>> from pwn import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwn/toplevel.py", line 20, in <module>
    import pwnlib
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/__init__.py", line 43, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/home/faraaz/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/args.py", line 61, in <module>
    from pwnlib import term
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/term/__init__.py", line 5, in <module>
    from pwnlib.term import completer
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/term/completer.py", line 6, in <module>
    from pwnlib.term import readline
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/term/readline.py", line 7, in <module>
    from pwnlib.term import term
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/term/term.py", line 167
    def goto((r, c)):
             ^
SyntaxError: invalid syntax

```

**Comment by faraazahmad** [comment]
I have a similar problem

```
>>> from pwn import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwn/toplevel.py", line 20, in <module>
    import pwnlib
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/__init__.py", line 43, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/home/faraaz/anaconda3/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/args.py", line 61, in <module>
    from pwnlib import term
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/term/__init__.py", line 5, in <module>
    from pwnlib.term import completer
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/term/completer.py", line 6, in <module>
    from pwnlib.term import readline
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/term/readline.py", line 7, in <module>
    from pwnlib.term import term
  File "/home/faraaz/anaconda3/lib/python3.6/site-packages/pwnlib/term/term.py", line 167
    def goto((r, c)):
             ^
SyntaxError: invalid syntax

```

**Comment by EvanCarroll** [comment]
@faraazahmad not similar, that's addressed here https://github.com/Gallopsled/pwntools/issues/1092

**Comment by heapcrash** [comment]
Closing this out since the PR is two+ years old and this is likely an editor / IDE-related issue.

A Pull Request would be welcomed!
