### ISSUE TITLE
Couldn't check security settings 

### ISSUE THREAD

**Issue by sizu91** [Gallopsled/pwntools#1151]
# Error in ssh 

## Original Error : 

I did this : 
```
>>> ss = ssh(user="atwari", host="10.10.4.122", keyfile="/home/sizu/.ssh/id_rsa")
[x] Connecting to 10.10.4.122 on port 22
[+] Connecting to 10.10.4.122 on port 22: Done
[!] Couldn't check security settings on '10.10.4.122'
>>> 
```

So, for getting full output I did this, export `PWNLIB_DEBUG=1`

and now I'm getting some error in even importing **pwntools**

```
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwn import *
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/usr/local/lib/python2.7/dist-packages/pwn/toplevel.py", line 20, in <module>
    import pwnlib
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/__init__.py", line 43, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/asm.py", line 59, in <module>
    from pwnlib import shellcraft
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/shellcraft/__init__.py", line 8, in <module>
    from pwnlib import constants
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/constants/__init__.py", line 61, in <module>
    from pwnlib.util import safeeval
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/util/__init__.py", line 3, in <module>
    from pwnlib.util import crc
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/util/crc/__init__.py", line 19, in <module>
    from pwnlib.util import fiddling
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/util/fiddling.py", line 12, in <module>
    from pwnlib.log import getLogger
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/log.py", line 646, in <module>
    log_file = LogfileHandler()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/log.py", line 633, in __init__
    super(LogfileHandler, self).__init__('', delay=1)
  File "/usr/lib/python2.7/logging/__init__.py", line 903, in __init__
    self.baseFilename = os.path.abspath(filename)
  File "/usr/lib/python2.7/posixpath.py", line 364, in abspath
    cwd = os.getcwd()
OSError: [Errno 2] No such file or directory
>>> 
```

Thanks :smile:

**Comment by Arusekk** [comment]
The [`getcwd(3)`](https://linux.die.net/man/3/getcwd) system call fails with `ENOENT` when the working directory gets deleted somehow. It might not be connected to pwntools, but another process deleting the directory in which python was started. Try doing `import os; os.chdir("/")` before importing the library.

**Comment by zachriggle** [comment]
"Couldn't check security settings" is a warning, not an error.

It just means we could not detect the arch / distro / version / ASLR state of the remote machine.

You can ignore the warning.

Regarding the "No such file or directory", I suspect @Arusekk is correct and there's an issue with the directory you're running Python from.

**Comment by Arusekk** [comment]
Closing this, too little info to do anything smart. Feel free to reopen.
