### ISSUE TITLE
`intervaltree` broked `ELF` class

### ISSUE THREAD

**Issue by Inndy** [Gallopsled/pwntools#1154]
```Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/elf/elf.py", line 206, in __init__
    self._populate_memory()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/elf/elf.py", line 978, in _populate_memory
    self.memory.chop(start, stop_data)
  File "/usr/local/lib/python2.7/dist-packages/intervaltree/intervaltree.py", line 508, in chop
    self.remove_envelop(begin, end)
  File "/usr/local/lib/python2.7/dist-packages/intervaltree/intervaltree.py", line 484, in remove_envelop
    hitlist = self.search(begin, end, strict=True)
  File "/usr/local/lib/python2.7/dist-packages/intervaltree/intervaltree.py", line 806, in search
    boundary_table.iloc[index] for index in xrange(bound_begin, bound_end)
  File "/usr/local/lib/python2.7/dist-packages/intervaltree/node.py", line 285, in search_overlap
    for j in point_list:
  File "/usr/local/lib/python2.7/dist-packages/intervaltree/intervaltree.py", line 806, in <genexpr>
    boundary_table.iloc[index] for index in xrange(bound_begin, bound_end)
AttributeError: 'SortedDict' object has no attribute 'iloc'
```

`ELF` class will be broken if `intervaltree>=2.0.2`, `intervaltree<=2.0.1` works fine.

**Comment by zachriggle** [comment]
Thanks for filing the bug!

Do you know if this is an issue with how Pwntools uses intervaltree? Or
just an issue with intervaltree itself.

If the latter, have you filed an intervaltree bug?

We’ll try to push out a hot fix soon!

**Comment by sandikast** [comment]
The same issue, with pwntools 3.12.0

**Comment by Inndy** [comment]
It's a bug from `intervaltree` due to its dependency `sortedcontainers` changed their API. I think they are working on this issue.

ref: https://github.com/chaimleib/intervaltree/issues/68
