### ISSUE TITLE
PyPI install a buggy version of capstone automatically

### ISSUE THREAD

**Issue by acdxvfsvd** [Gallopsled/pwntools#1160]
After installing it with ```pip install pwntools``` on a new virtual machine, I used the ```ROPgadget``` command but received an error message:
```
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/ROPgadget", line 15, in <module>
    import ropgadget
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ropgadget/__init__.py", line 14, in <module>
    import ropgadget.binary
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ropgadget/binary.py", line 13, in <module>
    from ropgadget.loaders.elf       import *
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ropgadget/loaders/__init__.py", line 13, in <module>
    import ropgadget.loaders.elf
  File "/home/ubuntu/.local/lib/python2.7/site-packages/ropgadget/loaders/elf.py", line 13, in <module>
    from capstone   import *
  File "/home/ubuntu/.local/lib/python2.7/site-packages/capstone/__init__.py", line 230, in <module>
    raise ImportError("ERROR: fail to load the dynamic library.")
```

I googled it and found that it was a bug in ```capstone 3.0.4``` but PyPI automatically installed it. 
Could you please update the requirements on ```PyPI``` to ```capstone>=3.0.5rc2``` ?

**Comment by zachriggle** [comment]
I just checked out the release notes, that should be fine.  Would you mind creating a pull request against the `stable` branch for this?
