### ISSUE TITLE
Cannot use ssh in Ubuntu 16.04

### ISSUE THREAD

**Issue by omretterry** [Gallopsled/pwntools#1184]
User ssh error in Ubuntu 16.04
`
[-] Connecting to pwnable.kr on port 2222: Failed
Traceback (most recent call last):
  File "./lotto.py", line 5, in <module>
    sh = ssh(host='pwnable.kr',user='lotto',password='guest',port=2222)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/pwnlib/tubes/ssh.py", line 606, in __init__
    self.client.connect(host, port, user, password, key, keyfiles, self.timeout, compress = True)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/client.py", line 392, in connect
    t.start_client(timeout=timeout)
  File "/home/ubuntu/.local/lib/python2.7/site-packages/paramiko/transport.py", line 545, in start_client
    raise e
AttributeError: '_EllipticCurvePublicKey' object has no attribute 'verify'
`

But success in 14.04 docker test container.May the reference package error？

`
[x] Connecting to pwnable.kr on port 2222
[+] Connecting to pwnable.kr on port 2222: Done
[*] lotto@pwnable.kr:
    Distro    Ubuntu 16.04
    OS:       linux
    Arch:     amd64
    Version:  4.10.0
    ASLR:     Enabled
`

**Comment by omretterry** [comment]
Downgrade the paramike version to 2.1.2 and solve the problem.
