### ISSUE TITLE
Can't properly use pwntools at kali, ubuntu 18.04 or debian stable

### ISSUE THREAD

**Issue by stuk0v** [Gallopsled/pwntools#1197]
using ubuntu 18.04, debian stable (strech), or kali 64bit, all have the same issue:
```
# pip install --upgrade pwntools
Requirement already up-to-date: pwntools in /usr/local/lib/python2.7/dist-packages (3.14.0.dev0)
Requirement already satisfied, skipping upgrade: tox>=1.8.1 in /usr/local/lib/python2.7/dist-packages (from pwntools) (3.3.0)
Requirement already satisfied, skipping upgrade: psutil>=3.3.0 in /usr/local/lib/python2.7/dist-packages (from pwntools) (5.4.7)
Requirement already satisfied, skipping upgrade: python-dateutil in /usr/local/lib/python2.7/dist-packages (from pwntools) (2.7.3)
Requirement already satisfied, skipping upgrade: pip>=6.0.8 in /usr/local/lib/python2.7/dist-packages (from pwntools) (18.0)
Requirement already satisfied, skipping upgrade: requests>=2.0 in /usr/local/lib/python2.7/dist-packages (from pwntools) (2.19.1)
Requirement already satisfied, skipping upgrade: sortedcontainers<2.0 in /usr/local/lib/python2.7/dist-packages (from pwntools) (1.5.10)
Requirement already satisfied, skipping upgrade: intervaltree in /usr/local/lib/python2.7/dist-packages (from pwntools) (2.1.0)
Requirement already satisfied, skipping upgrade: unicorn in /usr/local/lib/python2.7/dist-packages (from pwntools) (1.0.1)
Requirement already satisfied, skipping upgrade: capstone>=3.0.5rc2 in /usr/local/lib/python2.7/dist-packages (from pwntools) (3.0.5)
Requirement already satisfied, skipping upgrade: pysocks in /usr/local/lib/python2.7/dist-packages (from pwntools) (1.6.8)
Requirement already satisfied, skipping upgrade: pygments>=2.0 in /usr/local/lib/python2.7/dist-packages (from pwntools) (2.2.0)
Requirement already satisfied, skipping upgrade: mako>=1.0.0 in /usr/local/lib/python2.7/dist-packages (from pwntools) (1.0.7)
Requirement already satisfied, skipping upgrade: pyelftools>=0.2.4 in /usr/local/lib/python2.7/dist-packages (from pwntools) (0.25)
Requirement already satisfied, skipping upgrade: paramiko>=1.15.2 in /usr/local/lib/python2.7/dist-packages (from pwntools) (2.4.1)
Requirement already satisfied, skipping upgrade: ropgadget>=5.3 in /usr/local/lib/python2.7/dist-packages (from pwntools) (5.4)
Requirement already satisfied, skipping upgrade: packaging in /usr/local/lib/python2.7/dist-packages (from pwntools) (17.1)
Requirement already satisfied, skipping upgrade: pyserial>=2.7 in /usr/local/lib/python2.7/dist-packages (from pwntools) (3.4)
Requirement already satisfied, skipping upgrade: py<2,>=1.4.17 in /usr/local/lib/python2.7/dist-packages (from tox>=1.8.1->pwntools) (1.6.0)
Requirement already satisfied, skipping upgrade: toml>=0.9.4 in /usr/local/lib/python2.7/dist-packages (from tox>=1.8.1->pwntools) (0.9.6)
Requirement already satisfied, skipping upgrade: pluggy<1,>=0.3.0 in /usr/local/lib/python2.7/dist-packages (from tox>=1.8.1->pwntools) (0.7.1)
Requirement already satisfied, skipping upgrade: setuptools>=30.0.0 in /usr/lib/python2.7/dist-packages (from tox>=1.8.1->pwntools) (33.1.1)
Requirement already satisfied, skipping upgrade: six<2,>=1.0.0 in /usr/lib/python2.7/dist-packages (from tox>=1.8.1->pwntools) (1.10.0)
Requirement already satisfied, skipping upgrade: virtualenv>=1.11.2 in /usr/local/lib/python2.7/dist-packages (from tox>=1.8.1->pwntools) (16.0.0)
Requirement already satisfied, skipping upgrade: idna<2.8,>=2.5 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0->pwntools) (2.7)
Requirement already satisfied, skipping upgrade: urllib3<1.24,>=1.21.1 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0->pwntools) (1.23)
Requirement already satisfied, skipping upgrade: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0->pwntools) (3.0.4)
Requirement already satisfied, skipping upgrade: certifi>=2017.4.17 in /usr/local/lib/python2.7/dist-packages (from requests>=2.0->pwntools) (2018.8.24)
Requirement already satisfied, skipping upgrade: MarkupSafe>=0.9.2 in /usr/local/lib/python2.7/dist-packages (from mako>=1.0.0->pwntools) (1.0)
Requirement already satisfied, skipping upgrade: pynacl>=1.0.1 in /usr/local/lib/python2.7/dist-packages (from paramiko>=1.15.2->pwntools) (1.2.1)
Requirement already satisfied, skipping upgrade: cryptography>=1.5 in /usr/lib/python2.7/dist-packages (from paramiko>=1.15.2->pwntools) (1.7.1)
Requirement already satisfied, skipping upgrade: bcrypt>=3.1.3 in /usr/local/lib/python2.7/dist-packages (from paramiko>=1.15.2->pwntools) (3.1.4)
Requirement already satisfied, skipping upgrade: pyasn1>=0.1.7 in /usr/lib/python2.7/dist-packages (from paramiko>=1.15.2->pwntools) (0.1.9)
Requirement already satisfied, skipping upgrade: pyparsing>=2.0.2 in /usr/local/lib/python2.7/dist-packages (from packaging->pwntools) (2.2.0)
Requirement already satisfied, skipping upgrade: cffi>=1.4.1 in /usr/local/lib/python2.7/dist-packages (from pynacl>=1.0.1->paramiko>=1.15.2->pwntools) (1.11.5)
Requirement already satisfied, skipping upgrade: pycparser in /usr/local/lib/python2.7/dist-packages (from cffi>=1.4.1->pynacl>=1.0.1->paramiko>=1.15.2->pwntools) (2.18)
```

```
root@kali:~# apt-get install python2.7 python-pip python-dev git libssl-dev libffi-dev build-essential
Reading package lists... Done
Building dependency tree       
Reading state information... Done
build-essential is already the newest version (12.5).
git is already the newest version (1:2.18.0-1).
libffi-dev is already the newest version (3.2.1-8).
libssl-dev is already the newest version (1.1.0h-4).
python-dev is already the newest version (2.7.15-3).
python-pip is already the newest version (9.0.1-2.3).
python2.7 is already the newest version (2.7.15-4).
0 upgraded, 0 newly installed, 0 to remove and 10 not upgraded.
```

```
root@kali:~# pip install --upgrade pip
Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (18.0)
```

This is what happens when i test the installation (the output is exactly the same at all 3 installations I mentioned):
```
root@kali:~#  python -c 'from pwn import *'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/usr/local/lib/python2.7/dist-packages/pwn/toplevel.py", line 20, in <module>
    import pwnlib
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/__init__.py", line 43, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/dynelf.py", line 56, in <module>
    from pwnlib import elf
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/elf/__init__.py", line 9, in <module>
    from pwnlib.elf.corefile import Core
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/elf/corefile.py", line 84, in <module>
    from pwnlib.elf.elf import ELF
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/elf/elf.py", line 54, in <module>
    from elftools.elf.enums import ENUM_P_TYPE
ImportError: cannot import name ENUM_P_TYPE

```

**Comment by zachriggle** [comment]
Released pwntools==3.12.1, please update!
