### ISSUE TITLE
remote debug with docker failed

### ISSUE THREAD

**Issue by thinkycx** [Gallopsled/pwntools#1286]
# Environment
- macOS 11
- docker ubuntu 16.04
- python 2.17.12
- pwntool 3.12.2

# Problem 
When use pycharm to remote run python scripts which import pwntools, it hangs at `from pwn import *`.
And the output is : 
```
ssh://root@localhost:20022/usr/bin/python -u /tmp/pycharm_project_93/shellguard.py ./samples/heapcreator
Traceback (most recent call last):
  File "/tmp/pycharm_project_93/shellguard.py", line 6, in <module>
    from pwn import *
  File "/usr/local/lib/python2.7/dist-packages/pwn/__init__.py", line 6, in <module>
    pwnlib.args.initialize()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/args.py", line 208, in initialize
    term.init()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/term/__init__.py", line 74, in init
    term.init()
  File "/usr/local/lib/python2.7/dist-packages/pwnlib/term/term.py", line 109, in init
    c = os.read(fd.fileno(), 1)
KeyboardInterrupt

Process finished with exit code 1
```

It seems that the pwntools cannot read from the fd, Do you know why?
Could it be solved and be runned in  Pycham remote interpreter?

**Comment by thinkycx** [comment]
I gave up this way to debug pwntools  and debug it on macOS locally.
