### ISSUE TITLE
Installation fails on Arch Linux

### ISSUE THREAD

**Issue by 766F6964** [Gallopsled/pwntools#1336]
Trying to install pwntools on Manjaro x64, Kernel: 4.19.62-1-MANJARO results in the following exception being thrown:

```
void@void-pc :: ~ $ sudo pip install --upgrade pwntools
Collecting pwntools
  Using cached https://files.pythonhosted.org/packages/f1/a6/530d4a54d97a168a7500044be8d3dacbc42a32f05f8bedab5ad2b450263d/pwntools-3.12.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-roso1ise/pwntools/setup.py'"'"'; __file__='"'"'/tmp/pip-install-roso1ise/pwntools/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-roso1ise/pwntools/
    Complete output (41 lines):
    tar (child): data.tar.gz: Cannot open: No such file or directory
    tar (child): Error is not recoverable: exiting now
    tar: Child returned status 2
    tar: Error is not recoverable: exiting now
    * Downloading pandoc from https://github.com/jgm/pandoc/releases/download/2.7.3/pandoc-2.7.3-1-amd64.deb ...
    * Unpacking pandoc-2.7.3-1-amd64.deb to tempfolder...
    See http://johnmacfarlane.net/pandoc/installing.html
    for installation options
    ---------------------------------------------------------------
    
    Traceback (most recent call last):
      File "/tmp/pip-install-roso1ise/pwntools/setup.py", line 76, in <module>
        pypandoc.get_pandoc_path()
      File "/usr/lib/python3.7/site-packages/pypandoc/__init__.py", line 457, in get_pandoc_path
        _ensure_pandoc_path()
      File "/usr/lib/python3.7/site-packages/pypandoc/__init__.py", line 544, in _ensure_pandoc_path
        raise OSError("No pandoc was found: either install pandoc and add it\n"
    OSError: No pandoc was found: either install pandoc and add it
    to your PATH or or call pypandoc.download_pandoc(...) or
    install pypandoc wheels with included pandoc.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/tmp/pip-install-roso1ise/pwntools/setup.py", line 78, in <module>
        pypandoc.download_pandoc()
      File "/usr/lib/python3.7/site-packages/pypandoc/pandoc_download.py", line 207, in download_pandoc
        unpack(filename, targetfolder)
      File "/usr/lib/python3.7/site-packages/pypandoc/pandoc_download.py", line 86, in _handle_linux
        subprocess.check_call(cmd)
      File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['tar', 'xzf', 'data.tar.gz']' returned non-zero exit status 2.
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-roso1ise/pwntools/setup.py", line 83, in <module>
        print >>sys.stderr, "Failed to convert README.md through pandoc, proceeding anyway"
    TypeError: unsupported operand type(s) for >>: 'builtin_function_or_method' and '_io.TextIOWrapper'. Did you mean "print(<message>, file=<output_stream>)"?
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
How can I resolve this issue?

**Comment by 766F6964** [comment]
Installing pandoc manually seems to have resolved the issue (`sudo pacman -S pandoc`).

**Comment by ysf** [comment]
I suggest installing pwntools on manjaro / archlinux through the corresponding AUR packages using yay or another paketmanager https://aur.archlinux.org/packages/?K=pwntools&SB=p
