### ISSUE TITLE
Cannot connect via ssh

### ISSUE THREAD

**Issue by M0S4YSH3LL0** [Gallopsled/pwntools#1365]
I'm using Ubuntu 16.04, everything is fine but ssh tube doesn't work, and i can't figure out what to change to fix it.

here is my script:
`from pwn import *

p = ssh(host='e01.zenysec.com', user='ch03', password='ch03', port=20001)`

which results in:

`[-] Connecting to e01.zenysec.com on port 20001: Failed
Traceback (most recent call last):
  File "experiment.py", line 3, in <module>
    p = ssh(host='e01.zenysec.com', user='ch03', password='ch03', port=20001) #process('./ch03')
  File "/home/user1/.local/lib/python2.7/site-packages/pwnlib/tubes/ssh.py", line 606, in __init__
    self.client.connect(host, port, user, password, key, keyfiles, self.timeout, compress = True)
  File "/home/user1/.local/lib/python2.7/site-packages/paramiko/client.py", line 424, in connect
    passphrase,
  File "/home/user1/.local/lib/python2.7/site-packages/paramiko/client.py", line 686, in _auth
    filename, pkey_class, passphrase,
  File "/home/user1/.local/lib/python2.7/site-packages/paramiko/client.py", line 551, in _key_from_filepath
    key = klass.from_private_key_file(key_path, password)
  File "/home/user1/.local/lib/python2.7/site-packages/paramiko/pkey.py", line 206, in from_private_key_file
    key = cls(filename=filename, password=password)
  File "/home/user1/.local/lib/python2.7/site-packages/paramiko/rsakey.py", line 48, in __init__
    self._from_private_key_file(filename, password)
  File "/home/user1/.local/lib/python2.7/site-packages/paramiko/rsakey.py", line 169, in _from_private_key_file
    data = self._read_private_key_file('RSA', filename, password)
  File "/home/user1/.local/lib/python2.7/site-packages/paramiko/pkey.py", line 279, in _read_private_key_file
    data = self._read_private_key(tag, f, password)
  File "/home/user1/.local/lib/python2.7/site-packages/paramiko/pkey.py", line 337, in _read_private_key
    return decryptor.update(data) + decryptor.finalize()
  File "/home/user1/.local/lib/python2.7/site-packages/cryptography/hazmat/primitives/ciphers/base.py", line 149, in update
    return self._ctx.update(data)
  File "/home/user1/.local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 120, in update
    n = self.update_into(data, buf)
  File "/home/user1/.local/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/ciphers.py", line 131, in update_into
    "unsigned char *", self._backend._ffi.from_buffer(buf)
TypeError: from_buffer() cannot return the address of the raw string within a str or unicode or bytearray object`

if you need further information, i can provide it, thanks in advance.

**Comment by Arusekk** [comment]
Which version are you using? Also, are the libraries (paramiko, cryptography) updated? Is your password a password for the server or for the keyfile?

**Comment by M0S4YSH3LL0** [comment]
Library versions are:
cryptography-2.8
paramiko-2.6.0

Pwntools version: 3.12.2

password is password for the server

**Comment by Arusekk** [comment]
This should work in the newest pwntools, please reopen if the problem persists.
