### ISSUE TITLE
import error within python in GDB

### ISSUE THREAD

**Issue by Yuuoniy** [Gallopsled/pwntools#1372]
hi，developers:

I have some trouble with importing pwntools within the pythongdb on ubuntu 16.04( say I am using python in gdb)
```
gdb-peda$ python
>from pwn import *
>end
Traceback (most recent call last):
  File "<string>", line 4, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/usr/local/lib/python3.6/dist-packages/pwn/toplevel.py", line 20, in <module>
    import pwnlib
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/__init__.py", line 43, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/args.py", line 62, in <module>
    from pwnlib import term
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/term/__init__.py", line 6, in <module>
    from pwnlib.term import completer
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/term/completer.py", line 7, in <module>
    from pwnlib.term import readline
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/term/readline.py", line 9, in <module>
    from pwnlib.term import text
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/term/text.py", line 126, in <module>
    sys.modules[__name__] = Module()
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/term/text.py", line 49, in __init__
    s = termcap.get(y)
  File "/usr/local/lib/python3.6/dist-packages/pwnlib/term/termcap.py", line 27, in get
    s = curses.tigetstr(cap)
_curses.error: must call (at least) setupterm() first
Error while executing Python code.
```
outside gdb, I confirmed that pwntools has been installed successfully:

```
root@3fa8f1b25e93:/aeg/heap/unlink/2016_zctf_note2# python3
Python 3.6.8 (default, Oct  7 2019, 12:59:55) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pwn
>>> print(pwn.__file__)
/usr/local/lib/python3.6/dist-packages/pwn/toplevel.py
```
and I just installed the newest version pwntools by
`python3 -m pip install --upgrade git+https://github.com/Gallopsled/pwntools.git@dev3` 

I've checked that both the python include path are `/usr/local/lib/python3.6/`, but I can't import pwn inside gdb, while outside gdb, it worked.

I've tried several methods to solve it.  such as 
```
export TERM=linux; 
export TERMINFO=/etc/terminfo
```
but I still get trapped. Could you please help me with it?

**Comment by Yuuoniy** [comment]
solved it by setting `PWNLIB_NOTERM=true`
