### ISSUE TITLE
Python3: pdb is broken

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1406]
When using Pwntools 4.0.0 with Python3, there appear to be multiple issues when stepping with `pdb`.  In particular, the below issue arises.  I think this is related to terminal handling, since `NOTERM` resolves the issue.

### `pdb-broken.py`
```python3
#!/usr/bin/env python3 -m pdb
import time
from pwn import *
x=1
x=2
x=3
x=4
```

## Without Pwntools, the `q` command works

```
~ ❯❯❯ ./pdb-broken.py
> /Users/zachriggle/pdb-broken.py(2)<module>()
-> import time
(Pdb) n
> /Users/zachriggle/pdb-broken.py(3)<module>()
-> from pwn import *
(Pdb) q
```

## With pwntools, the `n` command works but `q` throws an exception

```
~ ❯❯❯ ./pdb-broken.py
> /Users/zachriggle/pdb-broken.py(2)<module>()
-> import time
(Pdb) n
> /Users/zachriggle/pdb-broken.py(3)<module>()
-> from pwn import *
(Pdb)
> /Users/zachriggle/pdb-broken.py(4)<module>()
-> x=1
(Pdb) q
Traceback (most recent call last):
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/pdb.py", line 1701, in main
    pdb._runscript(mainpyfile)
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/pdb.py", line 1570, in _runscript
    self.run(statement)
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/bdb.py", line 585, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/Users/zachriggle/pdb-broken.py", line 4, in <module>
    x=1
  File "/Users/zachriggle/pdb-broken.py", line 4, in <module>
    x=1
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/bdb.py", line 88, in trace_dispatch
    return self.dispatch_line(frame)
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/bdb.py", line 112, in dispatch_line
    self.user_line(frame)
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/pdb.py", line 261, in user_line
    self.interaction(frame, None)
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/pdb.py", line 352, in interaction
    self._cmdloop()
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/pdb.py", line 321, in _cmdloop
    self.cmdloop()
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/cmd.py", line 137, in cmdloop
    line = self.precmd(line)
  File "/Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/pdb.py", line 402, in precmd
    marker = line.find(';;')
TypeError: argument should be integer or bytes-like object, not 'str'
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /Users/zachriggle/.pyenv/versions/3.7.4/lib/python3.7/pdb.py(402)precmd()
-> marker = line.find(';;')
(Pdb)
```

**Comment by Arusekk** [comment]
This should be fixed, overwriting stdin with something that returns incompatible types is irresponsible. When I have more time, I can have a look into this
