### ISSUE TITLE
GitHub Actions failing for some reason (ADB)

### ISSUE THREAD

**Issue by Arusekk** [Gallopsled/pwntools#1455]
I made quite an effort to use GH Actions, but there is still that weird issue with ADB transport failing with some `device offline` error message.

Here is the link for error message:
https://github.com/Arusekk/pwntools/runs/514944460?check_suite_focus=true#step:13:565

**Comment by zachriggle** [comment]
I expect this is due to the Android SDK being out-of-date and only working on Travis because it's cached.  What happens if you try to run it in a Docker container? (`make -C travis/docker ANDROID=yes`)

**Comment by zachriggle** [comment]
It looks like it runs from the Dockerfile that's designed for testing locally.

```
 ---> 7c6997bd3af1
Successfully built 7c6997bd3af1
Successfully tagged travis:latest
docker run -e "ANDROID=yes" -e "TARGET=""" --rm --init --privileged -it travis
 * Starting OpenBSD Secure Shell server sshd                                                                                                                                                                  [ OK ]
* daemon not running; starting now at tcp:5037
* daemon started successfully
emulator: WARNING: Increasing RAM size to 1GB
emulator: UpdateChecker: skipped version check
### WARNING: could not find /usr/share/zoneinfo/ directory. unable to determine host timezone
generic/sdk_phone_armv7/generic:5.0.2/LSY66K/3079185:eng/test-keys
Running Sphinx v2.4.4
...
Automatically selecting device emulator-5554
```

It does look like the tests fail for Android, though:

```
Document: protocols/adb
-----------------------
**********************************************************************
File "../../pwnlib/protocols/adb/__init__.py", line ?, in default
Failed example:
    c.version() > (4,0)
Exception raised:
    Traceback (most recent call last):
      File "/home/travis/pwntools/pwnlib/tubes/sock.py", line 39, in recv_raw
        data = self.sock.recv(numb, *a)
    ConnectionResetError: [Errno 104] Connection reset by peer

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3.5/doctest.py", line 1321, in __run
        compileflags, 1), test.globs)
      File "<doctest default[0]>", line 1, in <module>
        c.version() > (4,0)
      File "/home/travis/pwntools/pwnlib/protocols/adb/__init__.py", line 124, in wrapper
        rv = fn(self, *a, **kw)
      File "/home/travis/pwntools/pwnlib/protocols/adb/__init__.py", line 188, in version
        response = self.send('host:version')
      File "/home/travis/pwntools/pwnlib/protocols/adb/__init__.py", line 148, in send
        return self.c.adb_send(*a, **kw)
      File "/home/travis/pwntools/pwnlib/protocols/adb/__init__.py", line 68, in adb_send
        return self.recvn(4)
      File "/home/travis/pwntools/pwnlib/tubes/tube.py", line 242, in recvn
        while self.countdown_active() and len(self.buffer) < numb and self._fillbuffer(self.timeout):
      File "/home/travis/pwntools/pwnlib/tubes/tube.py", line 131, in _fillbuffer
        data = self.recv_raw(self.buffer.get_fill_size())
      File "/home/travis/pwntools/pwnlib/tubes/sock.py", line 48, in recv_raw
        raise EOFError
    EOFError
```

**Comment by bet4it** [comment]
Travis could also fail : https://travis-ci.org/github/bet4it/pwntools/jobs/663012916#L7784

**Comment by Arusekk** [comment]
It was because killing ADB server did kill it, and it did not have time to get back up.
