### ISSUE TITLE
ELFError on Macos 10.14

### ISSUE THREAD

**Issue by shanzhuer** [Gallopsled/pwntools#1459]
i got an ELFError when i run checksec after command "gcc test.c".
(test.c is a very simple helloworld program)

$ checksec a.out 
Traceback (most recent call last):
  File "/usr/local/bin/checksec", line 11, in <module>
    load_entry_point('pwntools==4.0.1', 'console_scripts', 'checksec')()
  File "/usr/local/Cellar/pwntools/4.0.1_1/libexec/lib/python3.8/site-packages/pwnlib/commandline/common.py", line 32, in main
    pwnlib.commandline.main.main()
  File "/usr/local/Cellar/pwntools/4.0.1_1/libexec/lib/python3.8/site-packages/pwnlib/commandline/main.py", line 54, in main
    commands[args.command](args)
  File "/usr/local/Cellar/pwntools/4.0.1_1/libexec/lib/python3.8/site-packages/pwnlib/commandline/checksec.py", line 38, in main
    e = ELF(f.name)
  File "/usr/local/Cellar/pwntools/4.0.1_1/libexec/lib/python3.8/site-packages/pwnlib/elf/elf.py", line 213, in __init__
    super(ELF,self).__init__(self.mmap)
  File "/usr/local/Cellar/pwntools/4.0.1_1/libexec/lib/python3.8/site-packages/elftools/elf/elffile.py", line 67, in __init__
    self._identify_file()
  File "/usr/local/Cellar/pwntools/4.0.1_1/libexec/lib/python3.8/site-packages/elftools/elf/elffile.py", line 421, in _identify_file
    elf_assert(magic == b'\x7fELF', 'Magic number does not match')
  File "/usr/local/Cellar/pwntools/4.0.1_1/libexec/lib/python3.8/site-packages/elftools/common/utils.py", line 77, in elf_assert
    _assert_with_exception(cond, msg, ELFError)
  File "/usr/local/Cellar/pwntools/4.0.1_1/libexec/lib/python3.8/site-packages/elftools/common/utils.py", line 109, in _assert_with_exception
    raise exception_type(msg)
elftools.common.exceptions.ELFError: Magic number does not match

i installed pwntools and binutils successfully, what should i do now?

**Comment by Arusekk** [comment]
This is because mac OS executables are Mach-O format, not ELF. Checksec currently supports only ELFs (linux, *BSD).

**Comment by shanzhuer** [comment]
thx a lot
