### ISSUE TITLE
invalid syntax when running checksec

### ISSUE THREAD

**Issue by shanzhuer** [Gallopsled/pwntools#1461]
i got a invalid syntax when running checksec, i dont know why. there is no problem during installing pwntools.

~/pwn$ checksec stack1
Traceback (most recent call last):
  File "/usr/local/bin/checksec", line 11, in <module>
    load_entry_point('pwntools==4.2.0.dev0', 'console_scripts', 'checksec')()
  File "/usr/local/lib/python2.7/dist-packages/pwntools-4.2.0.dev0-py2.7.egg/pwnlib/commandline/common.py", line 29, in main
    import pwnlib.commandline.main
  File "/usr/local/lib/python2.7/dist-packages/pwntools-4.2.0.dev0-py2.7.egg/pwnlib/commandline/main.py", line 21, in <module>
    from pwnlib.commandline import template
  File "/usr/local/lib/python2.7/dist-packages/pwntools-4.2.0.dev0-py2.7.egg/pwnlib/commandline/template.py", line 10, in <module>
    from mako.lookup import TemplateLookup
  File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/lookup.py", line 12, in <module>
    from mako import exceptions
  File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/exceptions.py", line 305, in <module>
    _install_highlighting()
  File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/exceptions.py", line 300, in _install_highlighting
    _install_pygments()
  File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/exceptions.py", line 284, in _install_pygments
    from mako.ext.pygmentplugin import syntax_highlight  # noqa
  File "/usr/local/lib/python2.7/dist-packages/Mako-1.1.2-py2.7.egg/mako/ext/pygmentplugin.py", line 8, in <module>
    from pygments.formatters.html import HtmlFormatter
  File "/usr/local/lib/python2.7/dist-packages/Pygments-2.6.1-py2.7.egg/pygments/formatters/html.py", line 554
    file=sys.stderr)
        ^
SyntaxError: invalid syntax

**Comment by Arusekk** [comment]
A quick look shows that the syntax error is in Pygments, which seems to no longer be python2-compatible. Please file an issue there, seems that it's enough to do some `from __future__ import print_function` in their project where applicable.

**Comment by shanzhuer** [comment]
[pygments reply](https://github.com/pygments/pygments/issues/1419#issuecomment-602475737)
Pygments 2.6 has dropped support for Python 2.
but why pwntools-py2.7 still use it?

**Comment by Arusekk** [comment]
If pygments x.y are incompatible with py2, they should mark this on PyPI so that `pip2 install pygments` can install last supported release and not the broken one. As much as this is wrong to me and harmful to pwntools in py2, I can do really little about it.

**Comment by Arusekk** [comment]
Seems like they resolved this, `pip2 install pygments` installs v2.5.2. Please uninstall pygments, and install pwntools again.
