### ISSUE TITLE
Python3: ssh.process(...).corefile fails

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1468]
When running a process remotely via:

```
p = ssh.process(..., setuid=False)
```

... and crashing the process, one should be able to ...

```
p.wait()
p.corefile
```

However, the following exception is thrown on Python3:

```
[+] Downloading '/proc/sys/kernel/core_pattern': Found '/proc/sys/kernel/core_pattern' in ssh cache
[+] Downloading '/proc/sys/kernel/core_uses_pid': Found '/proc/sys/kernel/core_uses_pid' in ssh cache
[DEBUG] core_pattern: b'|/usr/share/apport/apport %p %s %c %d %P %E'
[DEBUG] core_uses_pid: False
[DEBUG] Not a process
[DEBUG] interpreter: ''
[DEBUG] Looking for QEMU corefile
Traceback (most recent call last):
  File "win.py", line 114, in <module>
    io.corefile
  File "/Users/zachriggle/github.com/pwntools/pwnlib/tubes/ssh.py", line 369, in corefile
    finder = pwnlib.elf.corefile.CorefileFinder(self)
  File "/Users/zachriggle/github.com/pwntools/pwnlib/elf/corefile.py", line 1187, in __init__
    self.core_path = self.qemu_corefile()
  File "/Users/zachriggle/github.com/pwntools/pwnlib/elf/corefile.py", line 1476, in qemu_corefile
    corefile_path = os.path.join(self.cwd, corefile_name)
  File "/Users/zachriggle/.pyenv/versions/3.8.2/lib/python3.8/posixpath.py", line 90, in join
    genericpath._check_arg_types('join', a, *p)
  File "/Users/zachriggle/.pyenv/versions/3.8.2/lib/python3.8/genericpath.py", line 155, in _check_arg_types
    raise TypeError("Can't mix strings and bytes in path components") from None
TypeError: Can't mix strings and bytes in path components
```

**Comment by zachriggle** [comment]
It looks like we're doing some weird concatenations of bytes and strings inside `CorefileFinder`.

This can be reproduced easily with:

```py
s=ssh('level1', 'io.netgarage.org', password='level1')
io=s.process(['bash', '-c', 'kill -SIGINT $$'])
io.wait()
io.corefile
```

I'm not familiar enough with mixing `bytes` and `str` objects, but I do see that we're doing weird things with formatting and getting incorrect values.

```
ipdb> up
> /Users/zachriggle/github.com/pwntools/pwnlib/elf/corefile.py(1476)qemu_corefile()
   1474
   1475         # Get the full path
-> 1476         corefile_path = os.path.join(self.cwd, corefile_name)
   1477
   1478         log.debug("Trying corefile_path: %r" % corefile_path)

ipdb> self.cwd
b'.'
ipdb> corefile_name
"qemu_b'bash'_*_9398.core"
```

**Comment by zachriggle** [comment]
It looks like this made it through the Python3'ificiation because there are no `CorefileFinder` tests.
