### ISSUE TITLE
install error about pandoc

### ISSUE THREAD

**Issue by shanzhuer** [Gallopsled/pwntools#1477]
~/pwntools$ sudo python3 setup.py install
Failed to convert README.md through pandoc, proceeding anyway
Traceback (most recent call last):
  File "setup.py", line 79, in <module>
    long_description = subprocess.check_output(['pandoc', 'README.md', '--to=rst'], universal_newlines=True)
  File "/usr/lib/python3.5/subprocess.py", line 626, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.5/subprocess.py", line 693, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.5/subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.5/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg)
FileNotFoundError: [Errno 2] No such file or directory: 'pandoc'

i hv exec pip3 install pandoc, but the error still occured.

**Comment by Arusekk** [comment]
This error is being displayed (not sure why), but it also prints "proceeding anyway", and proceeds. So your installation is most likely successful (or this is not the error that causes failure).
