### ISSUE TITLE
pause() is broken without arguments

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1530]
The `pause()` function takes an optional number of seconds to pause.

If no argument is given, it should wait until the user hits enter.

It is currently broken in different ways on Py2 and Py3:

## Py2

```
>>> pause()
[*] Paused (press enter to continue)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/pwntools/pwntools/pwnlib/ui.py", line 161, in pause
    raw_input('')
  File "/home/pwntools/pwntools/pwnlib/term/readline.py", line 436, in raw_input
    return readline(None, prompt, float)
  File "/home/pwntools/pwntools/pwnlib/term/readline.py", line 381, in readline
    print(prompt, end='', flush=True)
TypeError: 'flush' is an invalid keyword argument for this function
```

## Py3

```
>>> pause()
[*] Paused (press enter to continue)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/zachriggle/github.com/pwntools/pwnlib/ui.py", line 161, in pause
    raw_input('')
  File "/Users/zachriggle/github.com/pwntools/pwnlib/term/readline.py", line 436, in raw_input
    return readline(None, prompt, float)
  File "/Users/zachriggle/github.com/pwntools/pwnlib/term/readline.py", line 382, in readline
    return sys.stdin.readline(_size).rstrip('\n')
TypeError: 'NoneType' object cannot be interpreted as an integer
```

**Comment by Arusekk** [comment]
To be cherry-picked from ad0da0a67

**Comment by heapcrash** [comment]
This appears to be fixed on `dev`
