### ISSUE TITLE
muitiple thread bryteforce have bugs on Macos 10.15.5 with python3.8.5

### ISSUE THREAD

**Issue by fjh1997** [Gallopsled/pwntools#1665]
##  summary
system: Macos 10.15
python:3.8.5

in this util 
util.iters.mbruteforce(f, string.ascii_letters + string.digits, 3, 'fixed')

works well with python 3.7.4 both on ubuntu and macos
works well on Ubuntu with python 3.8.5,but have bugs on Macos with python 3.8.5 . 

## Error Output
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 125, in _main
    prepare(preparation_data)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 236, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 287, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 263, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/fjh1997/Desktop/bank.py", line 36, in <module>
    prefix = proof_of_work()
  File "/Users/fjh1997/Desktop/bank.py", line 31, in proof_of_work
    prefix = util.iters.mbruteforce(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pwnlib/util/iters.py", line 891, in mbruteforce
    shareddata[i] = multiprocessing.Manager().dict()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 579, in start
    self._process.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 154, in get_preparation_data
    _check_not_importing_main()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/spawn.py", line 134, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
Traceback (most recent call last):
  File "bank.py", line 36, in <module>
    prefix = proof_of_work()
  File "bank.py", line 31, in proof_of_work
    prefix = util.iters.mbruteforce(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pwnlib/util/iters.py", line 891, in mbruteforce
    shareddata[i] = multiprocessing.Manager().dict()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 57, in Manager
    m.start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/managers.py", line 583, in start
    self._address = reader.recv()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 414, in _recv_bytes
    buf = self._recv(4)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/connection.py", line 383, in _recv
    raise EOFError
EOFError
```
and then I try to put code under  ```if __name__ == '__main__:'```
the error become this
```
Traceback (most recent call last):
  File "bc1.py", line 40, in <module>
    prefix = proof_of_work()
  File "bc1.py", line 35, in proof_of_work
    prefix = util.iters.mbruteforce(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pwnlib/util/iters.py", line 902, in mbruteforce
    processes[i].start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'mbruteforce.<locals>.bruteforcewrap'
```

**Comment by soreatu** [comment]
same problem on MacOS 10.15.6 with python3.8

```python
[<] MBruteforcing
Traceback (most recent call last):
  File "exp.py", line 34, in <module>
    main()
  File "exp.py", line 31, in main
    proof_of_work(suffix, _hexdigest)
  File "exp.py", line 9, in proof_of_work
    prefix = mbruteforce(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pwnlib/util/iters.py", line 902, in mbruteforce
    processes[i].start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'mbruteforce.<locals>.bruteforcewrap'
```

**Comment by Arusekk** [comment]
Please check if #1685 fixes this issue (use `pip install git+https://github.com/Arusekk/pwntools@mbrute-pickling`).

**Comment by soreatu** [comment]
Sorry, this doesn't work.

After `python3 -m pip install git+https://github.com/Arusekk/pwntools@mbrute-pickling`, I tried to run my script, only to get the same error as before:
```shell
[o] MBruteforcing
Traceback (most recent call last):
  File "exp.py", line 63, in <module>
    main()
  File "exp.py", line 41, in main
    proof_of_work(conn)
  File "exp.py", line 16, in proof_of_work
    prefix = mbruteforce(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pwnlib/util/iters.py", line 902, in mbruteforce
    processes[i].start()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/context.py", line 283, in _Popen
    return Popen(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
AttributeError: Can't pickle local object 'proof_of_work.<locals>.<lambda>'
```

**Comment by Arusekk** [comment]
Wow, this is not what I expected of python multiprocessing. I am disappointed by the library's low quality here. Why the heck does it need to pickle your proof-of-work function??

Anyways, you can make your lambda into a separate function for now, and hope that it works. Not closing this bug, since it is really disturbing to see python pickle an object when both processes can just access it as it is. I will take a look at it and hopefully file a bug in Python interpreter itself.

**Comment by Arusekk** [comment]
The opposite thing is reported upstream in https://bugs.python.org/issue33725

They claim that there is no harm in using `spawn()` vs `fork()`, while there *certainly is*. `fork` spawns a new process with *≈everything* copied from the parent process, but `spawn()` starts a fresh process that does not even have stuff initialized. It is a miracle that multiprocessing with `spawn()` works in any use case at all, but since MacOS developers state that "forking is unsafe if you have multiple threads" (which is kinda true) "so we will not support it lol" (which is certainly boorish of them), Python devs have no choice but to use a different multiprocessing method by default. If you plan on more hacking from MacOS, your application has to adapt to the OS' view on supporting things.

The workaround I mentioned (combined with my PR #1685) is the only option we have left, so instead of:
```py
def proof_of_work([args 0]):
    ... stuff 1 ...
    prefix = mbruteforce(
        lambda [args 1]: [expression 1],
        [args 1 values],
        ... stuff 2 ...
```
you need to use:
```py
def this_is_not_a_lambda([args 1], [additional args since you no longer have
                                    access to local variables from proof_of_work]):
    return [expression 1]

def proof_of_work([args 0]):
    ... stuff 1 ...
    prefix = mbruteforce(
        this_is_not_a_lambda,
        [args 1 values + additional args values],
        ... stuff 2 ...
```

If it works, please let me know in order to give my changes a meaning :)

**Comment by soreatu** [comment]
Yes. It works by defining the lambda function outside (combined with #1685).

But another problem occurs, I need to send two more arguments (local variables in `proof_of_work`) to the function. However, the first argument of `mbruteforce` is a function that cannot receive more than **one** argument, as documented:
```markdown
Bruteforce `func` to return `True`. `func` should take a string input and return a `bool`. `func` will be called with strings from `alphabet` until it returns `True` or the search space has been exhausted.
```

I will try to find some way to solve this new problem. 😢 

Anyway, thanks for your excellent explaination and great solution. You certainly did something meaningful 👍 👍 👍

**Comment by fjh1997** [comment]
Just in `/usr/local/lib/python3.9/site-packages/pwnlib/util/iters.py` add a newline:
```python
"""
This module includes and extends the standard module :mod:`itertools`.
"""
from __future__ import absolute_import
from __future__ import division

import collections
import copy
import multiprocessing
multiprocessing.set_start_method('fork'). # add this line is Ok!
import operator
import random
import time
from itertools import *
from six.moves import map, filter, filt
```

See https://chrissardegna.com/blog/multiprocessing-changes-python-3-8/#python-38-safety-on-macos
and https://docs.python.org/3/library/multiprocessing.html

**Comment by heapcrash** [comment]
> but since MacOS developers state that "forking is unsafe if you have multiple threads" (which is kinda true) "so we will not support it lol"

It is almost always true that every process has multiple threads, specifically anything that touches XPC (everything touches XPC), anything that hosts XPC, or anything that uses Grand Central Dispatch (everything written since 2009).

Using `fork()` correctly even on Linux is hard.  Consider:

```
$ cat t.c
#include <math.h>
#include <stdarg.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <unistd.h>

int main() {
    printf("Hello, world");
    fork();
}

$ clang t.c

$ ./a.out | xxd
00000000: 4865 6c6c 6f2c 2077 6f72 6c64 4865 6c6c  Hello, worldHell
00000010: 6f2c 2077 6f72 6c64                      o, world
```

"Hello, world" is printed twice, because the internal state of line-buffered stdout (note there is no "\n" in the `printf`) means the buffer is copied, and the buffer is emptied in BOTH the parent and the child when they exit.

`fork()` is hard to do right, macOS worked around this with GCD and other mechanisms.
