### ISSUE TITLE
Tests appear broken due to os.devnull usage

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#1718]
It looks like the Travis CI tests are broken due to an exception, and GHA are broken due to a timeout.

The errors on both seem to be related to some new code in run_in_new_terminal, specifically setting stdin/stdout/stderr to all be the same copy of os.devnull.

## Travis CI

```
Document: elf/corefile
1001----------------------
1002**********************************************************************
1003File "../../pwnlib/elf/corefile.py", line ?, in default
1004Failed example:
1005    core = io.corefile
1006Exception raised:
1007    Traceback (most recent call last):
1008      File "/opt/python/3.8.0/lib/python3.8/doctest.py", line 1328, in __run
1009        exec(compile(example.source, filename, "single",
1010      File "<doctest default[3]>", line 1, in <module>
1011        core = io.corefile
1012      File "/home/travis/build/Gallopsled/pwntools/pwnlib/tubes/process.py", line 937, in corefile
1013        return pwnlib.gdb.corefile(self)
1014      File "/home/travis/build/Gallopsled/pwntools/pwnlib/gdb.py", line 1000, in corefile
1015        pid = attach(process, gdb_args=gdb_args)
1016      File "/home/travis/build/Gallopsled/pwntools/pwnlib/context/__init__.py", line 1457, in setter
1017        return function(*a, **kw)
1018      File "/home/travis/build/Gallopsled/pwntools/pwnlib/gdb.py", line 794, in attach
1019        gdb_pid = misc.run_in_new_terminal(cmd)
1020      File "/home/travis/build/Gallopsled/pwntools/pwnlib/util/misc.py", line 268, in run_in_new_terminal
1021        stdin = stdout = stderr = open(os.devnull, 'rwb')
1022    ValueError: must have exactly one of create/read/write/append mode
1023**********************************************************************
1024File "../../pwnlib/elf/corefile.py", line ?, in default
1025Failed example:
1026    core.exe[elf.address:elf.address+4]
1027Exception raised:
1028    Traceback (most recent call last):
1029      File "/opt/python/3.8.0/lib/python3.8/doctest.py", line 1328, in __run
1030        exec(compile(example.source, filename, "single",
1031      File "<doctest default[1]>", line 1, in <module>
1032        core.exe[elf.address:elf.address+4]
1033      File "/home/travis/build/Gallopsled/pwntools/pwnlib/elf/corefile.py", line 222, in __getitem__
1034        log.error("Byte range [%#x:%#x] not within range [%#x:%#x]",
1035      File "/home/travis/build/Gallopsled/pwntools/pwnlib/log.py", line 424, in error
1036        raise PwnlibException(message % args)
1037    pwnlib.exception.PwnlibException: Byte range [0x400000:0x400004] not within range [0x41410000:0x41411000]
1038**********************************************************************
1039File "../../pwnlib/elf/corefile.py", line ?, in default
1040Failed example:
1041    core.exe.data[:4]
1042Expected:
1043    b'\x7fELF'
1044Got:
1045    b'\xef\x0e\x0b\xe3'
1046
```

## Github Actions

```
Document: gdb
182
-------------
183
**********************************************************************
184
File "../../pwnlib/gdb.py", line ?, in default
185
Failed example:
186
    pid = gdb.attach(io, gdbscript='''
187
    call puts("Hello from process debugger!")
188
    detach
189
    quit
190
    ''')
191
Exception raised:
192
    Traceback (most recent call last):
193
      File "/opt/hostedtoolcache/Python/3.8.6/x64/lib/python3.8/doctest.py", line 1336, in __run
194
        exec(compile(example.source, filename, "single",
195
      File "<doctest default[1]>", line 1, in <module>
196
        pid = gdb.attach(io, gdbscript='''
197
      File "/home/runner/work/pwntools/pwntools/pwnlib/context/__init__.py", line 1457, in setter
198
        return function(*a, **kw)
199
      File "/home/runner/work/pwntools/pwntools/pwnlib/gdb.py", line 794, in attach
200
        gdb_pid = misc.run_in_new_terminal(cmd)
201
      File "/home/runner/work/pwntools/pwntools/pwnlib/util/misc.py", line 268, in run_in_new_terminal
202
        stdin = stdout = stderr = open(os.devnull, 'rwb')
203
    ValueError: must have exactly one of create/read/write/append mode
204
Error: The operation was canceled.
Coverage running examples
```

**Comment by Arusekk** [comment]
I fixed that already, but I forgot to `git push` the branch :man_facepalming: anyways, this should be fixed now with 0b1f430935842d23aa6f4027eea7ac1bb292bcc1
