### ISSUE TITLE
Issue when attempting to generate Coredump

### ISSUE THREAD

**Issue by wahost070** [Gallopsled/pwntools#1789]
Hi there, first bug report issue, so please bear with me.

I am following this guide "https://docs.pwntools.com/en/stable/elf/corefile.html", and have copied the code as I couldn't get it to work myself. It is still giving me the following error when I attempt to do a Coredump:

```python
Traceback (most recent call last):
  File "/home/binexp/Documents/Projects/RE_BinExp/PwnToolsPractice/win.py", line 7, in <module>
    process(['./crash', payload]).wait()
  File "/home/binexp/.local/lib/python3.9/site-packages/pwnlib/tubes/process.py", line 306, in __init__
    with self.progress(message) as p:
  File "/home/binexp/.local/lib/python3.9/site-packages/pwnlib/log.py", line 323, in progress
    return Progress(self, message, status, level, args, kwargs)
  File "/home/binexp/.local/lib/python3.9/site-packages/pwnlib/log.py", line 181, in __init__
    self._log(status, args, kwargs, 'status')
  File "/home/binexp/.local/lib/python3.9/site-packages/pwnlib/log.py", line 188, in _log
    status = six.ensure_text(status)
AttributeError: module 'six' has no attribute 'ensure_text'
      
```

I am on the latest version of both Python3 and Pwntools.

**Comment by peace-maker** [comment]
Make sure your `six` version is `>=1.12.0`. It seems to be too old.

**Comment by Arusekk** [comment]
`pip install -U six` or `pip install --user -U six` should do. The other thing is that I am not so happy with us using `six.ensure_text`. If you cannot install new six, you can just comment out this last reported line in pwntools.

**Comment by wahost070** [comment]
That did the trick. Thanks for the help!
