### ISSUE TITLE
GDB is mean to bytes in env

### ISSUE THREAD

**Issue by Arusekk** [Gallopsled/pwntools#1804]
GDB is unable to pass correct environment to the process.

Reported by `qwe` on Discord.
Reproducer:
```py
$ python3 -bb
>>> from pwn import *
>>> gdb.debug('env', env={'asdf': b'\xff\xff'})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/arusekk/src/my-git/pwntools/pwnlib/context/__init__.py", line 1457, in setter
    return function(*a, **kw)
  File "/home/arusekk/src/my-git/pwntools/pwnlib/gdb.py", line 505, in debug
    args = _gdbserver_args(args=args, which=which, env=env)
  File "/home/arusekk/src/my-git/pwntools/pwnlib/gdb.py", line 305, in _gdbserver_args
    env_args.append('{}="{}"'.format(key, env[key]))
BytesWarning: str() on a bytes instance
```

**Comment by heapcrash** [comment]
We should be setting the environment when we launch GDB via `process()` or `launch_in_new_terminal`, no?

**Comment by heapcrash** [comment]
Looks like we do manual injection of environment variables on the command line, which is probably not the best way to go about it, and there's some special-case handling of `LD_XXX` that is presumably popped to prevent `gdb` / `gdbserver` itself from having a library injected.

```
        for key in tuple(env):
            if key.startswith('LD_'): # LD_PRELOAD / LD_LIBRARY_PATH etc.
                env_args.append('{}="{}"'.format(key, env.pop(key)))
            else:
                env_args.append('{}="{}"'.format(key, env[key]))
```

We should be passing the environment dict directly to `gdbserver`'s instantiation, probably in `runner` here:

```
        gdb_cmd = _gdbserver_args(pid=pid, which=which, env=env)
         gdbserver = runner(gdb_cmd)
         port    = _gdbserver_port(gdbserver, None)
```

**Comment by heapcrash** [comment]
It appears that setting `env=` at all for `gdb.debug` is broken, because `--wrapper` is supposed to take a single argument, not a list of arguments.

```py
env={'PWNLIB_NOTERM': '1', 
     'HELLO': 'WORLD', }
cmd = ['bash', '-c', 'echo $HELLO | xxd']
io = gdb.debug(cmd, env=env)
io.recvall()
```

```
[+] Starting local process '/usr/bin/gdbserver' argv=['/usr/bin/gdbserver', '--multi', '--no-disable-randomization', '--wrapper', 'env', '-i', 'PWNLIB_NOTERM=1', 'HELLO=WORLD', '--', 'localhost:0', 'bash', '-c', 'echo $HELLO | xxd']  env={'PWNLIB_NOTERM': '1', 'HELLO': 'WORLD'} : pid 343
```

`--wrapper` takes a single file argument, not multiple arguments.

**Comment by heapcrash** [comment]
@Arusekk did #1896 close this?
