### ISSUE TITLE
process() explodes when creating progress message for QEMU cross-arch binaries

### ISSUE THREAD

**Issue by heapcrash** [Gallopsled/pwntools#1806]
Not really sure what's going on here.  This is happening on Python3 when attempting to run some of the SigReturn frame stuff.

According to the internet, u2524 is `┤ U+2524` which we shouldn't be emitting anywhere except maybe in a spinner?  **UPDATE** It turns out we do emit this character as a spinner, per `spinners.py`:

```py
    ['┤', '┘', '┴', '└', '├', '┌', '┬', '┐'],
```

Not sure why it's throwing the exception, though.

```py
#!/usr/bin/env python3
from pwn import *

context.arch = 'arm'
context.log_level = 'debug'
hello = "Hello, world!"
message = "%s %s" % (context.arch, hello)
assembly =  '\nread:'      + shellcraft.read(constants.STDIN_FILENO, 'sp', 1024)
assembly += '\nsigreturn:' + shellcraft.sigreturn()
assembly += '\nint3:'      + shellcraft.trap()
assembly += '\nsyscall: '  + shellcraft.syscall()
assembly += '\nexit: '     + 'eor r0, r0; mov r7, 0x1; swi #0;'
assembly += '\nmessage: '  + ('.asciz "%s"' % message)
binary = ELF.from_assembly(assembly)

print('================================')
frame = SigreturnFrame()
frame.r7 = constants.SYS_write
frame.r0 = constants.STDOUT_FILENO
frame.r1 = binary.symbols['message']
frame.r2 = len(message)
frame.sp = 0xdead0000
frame.pc = binary.symbols['syscall']
print('================================')
p = gdb.debug(binary.path)
print('================================')
sys.exit()
```

```
ipdb> list
    305
    306
    307         if 'qemu' in self.display:
    308             import ipdb; ipdb.set_trace()
    309
--> 310         with self.progress(message) as p:
    311
    312             if not self.aslr:
    313                 self.warn_once("ASLR is disabled!")
    314
    315             # In the event the binary is a foreign architecture,

ipdb> message
"Starting local process '/usr/bin/qemu-arm-static' argv=[b'qemu-arm-static', b'--help'] "
ipdb> type(message)
<class 'str'>
```

Single-stepping over the `self.progress` message throws a HUGE error message and erases part of the screen.

```
[> /home/pwntools/pwntools/pwnlib/tubes/process.py(312)__init__()
    311
--> 312             if not self.aslr:
    313                 self.warn_once("ASLR is disabled!")

ipdb> Exception in thread Thread-168:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pwntools/pwntools/pwnlib/log.py", line 557, in spin
    spinner_handle.update(prefix)
  File "/home/pwntools/pwntools/pwnlib/term/term.py", line 189, in update
    update(self.h, s)
  File "/home/pwntools/pwntools/pwnlib/term/term.py", line 538, in update
    render_from(i, clear_after = True)
  File "/home/pwntools/pwntools/pwnlib/term/term.py", line 456, in render_from
    render_cell(c, clear_after = clear_after)
  File "/home/pwntools/pwntools/pwnlib/term/term.py", line 359, in render_cell
    put(c)
  File "/home/pwntools/pwntools/pwnlib/term/term.py", line 166, in put
    fd.write(s)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2524' in position 0: ordinal not in range(128)
```

**Comment by heapcrash** [comment]
Looks like it's showing up still as part of hex dumping the data when sending it with `context.log_level='debug'`.

```
[DEBUG] Launching a new terminal: ['/usr/bin/tmux', 'splitw', '-F#{pane_pid}', '-P', '/usr/bin/gdb-multiarch -q  -x /tmp/pwnr1w26x9y.gdb']
================================
[DEBUG] Sent 0xf0 bytes:
--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib/python3.6/logging/__init__.py", line 996, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 66-86: ordinal not in range(128)
Call stack:
  File "pwntools/arm.py", line 29, in <module>
    p = gdb.debug(binary.path)
  File "/home/pwntools/pwntools/pwnlib/tubes/tube.py", line 776, in send
    self.indented(fiddling.hexdump(data), level = logging.DEBUG)
  File "/home/pwntools/pwntools/pwnlib/log.py", line 339, in indented
    self._log(level, message, args, kwargs, 'indented')
  File "/home/pwntools/pwntools/pwnlib/log.py", line 298, in _log
    self._logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 865, in handle
    self.emit(record)
  File "/home/pwntools/pwntools/pwnlib/log.py", line 535, in emit
    super(Handler, self).emit(record)
Message: '00000000  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  \u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\n00000010  00 00 00 00  06 00 00 00  00 00 00 00  00 00 00 00  \u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\n00000020  01 00 00 00  34 00 00 10  11 00 00 00  00 00 00 00  \u2502\xb7\xb7\xb7\xb7\u25024\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\n00000030  00 00 00 00  00 00 00 00  00 00 00 00  04 00 00 00  \u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\n00000040  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  \u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\n00000050  00 00 00 00  00 00 ad de  00 00 00 00  24 00 00 10  \u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502$\xb7\xb7\xb7\u2502\n00000060  10 00 00 40  00 00 00 00  00 00 00 00  00 00 00 00  \u2502\xb7\xb7\xb7@\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\n00000070  00 00 00 00  00 00 00 00  00 00 00 00  00 00 00 00  \u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\n*\n000000e0  00 00 00 00  00 00 00 00  01 50 46 56  20 01 00 00  \u2502\xb7\xb7\xb7\xb7\u2502\xb7\xb7\xb7\xb7\u2502\xb7PFV\u2502 \xb7\xb7\xb7\u2502\n000000f0'
Arguments: ()
```

**Comment by heapcrash** [comment]
Yeah it looks like `ipdb` puts the terminal into ASCII-only mode and it's choking on `hexdump` which has the character `│` to separate fields.

**Comment by heapcrash** [comment]
Yep.

```
ipdb> sys.stdout
<_io.TextIOWrapper name='<stdout>' mode='w' encoding='ANSI_X3.4-1968'>
```

**Comment by Arusekk** [comment]
what da, why is anyone overriding sys.stdout with a wrapper of a different encoding? Let's see what your LC_ALL, LC_CTYPE, LANG and such env variables are. Maybe we should issue a warning, like with [pwndbg]?

[pwndbg]: https://github.com/pwndbg/pwndbg/blob/4d213a1f90dd1b2f285947cf959f617f85ca5d98/gdbinit.py#L16

**Comment by heapcrash** [comment]
LC_ALL and LC_LANG were both unset, setting those fixed the issue.

This was all in a Dockerfile that's set up for running our CI, and those environment variables were not set -- the correct solution was to set them.  I now have:

```
# Do everything in UTF-8 mode!
ENV LANG=C.UTF-8
ENV LC_ALL=C.UTF-8
```
