### ISSUE TITLE
process stop when using tmux in pwntools 4.5.0

### ISSUE THREAD

**Issue by gtrboy** [Gallopsled/pwntools#1878]
## The Bug

When using tmux and gdb.attach() in pwntools 4.5.0, the process stopped when calling run_in_new_terminal in pwnlib/util/misc.py.

The test environment is the pwntools docker.

## exp1.py

```
from pwn import *
p = process("./hacknote")
context.terminal = ['tmux', 'splitw', '-h']
gdb.attach(p)
p.interactive()
```

## Debug Output
```sh
$ python3 exp1.py
[+] Starting local process './hacknote': pid 689
[*] running in new terminal: /usr/bin/gdb -q  "./hacknote" 689
Traceback (most recent call last):
  File "exp1.py", line 5, in <module>
    gdb.attach(p)
  File "/home/pwntools/.local/lib/python3.6/site-packages/pwnlib/context/__init__.py", line 1543, in setter
    return function(*a, **kw)
  File "/home/pwntools/.local/lib/python3.6/site-packages/pwnlib/gdb.py", line 1051, in attach
    gdb_pid = misc.run_in_new_terminal(cmd, preexec_fn = preexec_fn)
  File "/home/pwntools/.local/lib/python3.6/site-packages/pwnlib/util/misc.py", line 297, in run_in_new_terminal
    pid = int(out)
ValueError: invalid literal for int() with base 10: b''
[*] Stopped process './hacknote' (pid 689)
```

It seems that pwntools 4.5.0 uses subprocess instead of fork, and the error is because the output of p.communicate() function is None in line 296 of misc.py. Hence the int(out)  raises an ValueError.

**Comment by Arusekk** [comment]
dup of #1874 but not closing since that one is closed
