### ISSUE TITLE
 gdb.attach(pid) stuck at "waitting for debugger"

### ISSUE THREAD

**Issue by wgf4242** [Gallopsled/pwntools#1942]
[Solved] `pip install pwntools==4.4.0` and everything works.

---
Cannot get debugger in new window. And pwndbg in new window cannot run any command

Tested in Kali 2020.4, 2021.1 2021.2 ,

Run `gdb` in shell, then `attatch pid` manually work.
```
$ gdb
pwngdb $ attach pid
# switch to program, input something
$ ni
# stop at next line ---- works
```
```
$ gdb
pwngdb $ file level1
$ ni
# works fine
```

## Not work with script.

```
from pwn import *

io = process('./l1')
gdb.attach(io)
io.interactive()
```
## Debug Output

```

[+] Starting local process './l1' argv=[b'./l1'] : pid 5070
[*] running in new terminal: ['/usr/bin/gdb', '-q', './l1', '5070', '-x', '/tmp/pwn8v0m8rsc.gdb']
[DEBUG] Created script for new terminal:
    #!/usr/bin/python3
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './l1', '5070', '-x', '/tmp/pwn8v0m8rsc.gdb'], os.environ)
[DEBUG] Launching a new terminal: ['/usr/bin/x-terminal-emulator', '-e', '/tmp/tmpk_lw7no7']
arv is ['/usr/bin/x-terminal-emulator', '-e', '/tmp/tmpk_lw7no7']
[▖] Waiting for debugger

```

After Ctrl+C intterupt, info
```
└─$ python3 del3.py                                                                                                                                                                                     130 ⨯
[+] Starting local process './l1' argv=[b'./l1'] : pid 5325
id is  [5325]
id is  5325
[DEBUG] Wrote gdb script to '/tmp/pwnlzfysx6x.gdb'

        b *0x080484B6

[*] running in new terminal: ['/usr/bin/gdb', '-q', './l1', '5325', '-x', '/tmp/pwnlzfysx6x.gdb']
script is  ['/usr/bin/gdb', '-q', './l1', '5325', '-x', '/tmp/pwnlzfysx6x.gdb']
script is  ['/usr/bin/gdb', '-q', './l1', '5325', '-x', '/tmp/pwnlzfysx6x.gdb']
[DEBUG] Created script for new terminal:
    #!/usr/bin/python3
    import os
    os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './l1', '5325', '-x', '/tmp/pwnlzfysx6x.gdb'], os.environ)
script is  #!/usr/bin/python3
import os
os.execve('/usr/bin/gdb', ['/usr/bin/gdb', '-q', './l1', '5325', '-x', '/tmp/pwnlzfysx6x.gdb'], os.environ)

[DEBUG] Launching a new terminal: ['/usr/bin/x-terminal-emulator', '-e', '/tmp/tmpw9v3pfo6']
[-] Waiting for debugger: Failed
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 446, in wrapper
    ret = self._cache[fun]
AttributeError: _cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kali/vmware/pwn1/del3.py", line 19, in <module>
    gdb.attach(conn, gdbscript="""
  File "/home/kali/.local/lib/python3.9/site-packages/pwnlib/context/__init__.py", line 1524, in setter
    return function(*a, **kw)
  File "/home/kali/.local/lib/python3.9/site-packages/pwnlib/gdb.py", line 1049, in attach
    proc.wait_for_debugger(pid, gdb_pid)
  File "/home/kali/.local/lib/python3.9/site-packages/pwnlib/util/proc.py", line 337, in wait_for_debugger
    debugger = psutil.Process(debugger_pid)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 324, in __init__
    self._init(pid)
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 352, in _init
    self.create_time()
  File "/usr/lib/python3/dist-packages/psutil/__init__.py", line 708, in create_time
    self._create_time = self._proc.create_time()
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1517, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1729, in create_time
    ctime = float(self._parse_stat_file()['create_time'])
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1517, in wrapper
    return fun(self, *args, **kwargs)
  File "/usr/lib/python3/dist-packages/psutil/_common.py", line 449, in wrapper
    return fun(self)
  File "/usr/lib/python3/dist-packages/psutil/_pslinux.py", line 1560, in _parse_stat_file
    data = f.read()
KeyboardInterrupt
[*] Stopped process './l1' (pid 5325)

```

**Comment by Arusekk** [comment]
Does it work if you disable pwndbg? Does it work if you run it inside tmux? Or with `context.terminal` set to a different terminal?

**Comment by Reinose** [comment]
> Does it work if you disable pwndbg? Does it work if you run it inside tmux? Or with `context.terminal` set to a different terminal?

I'm suffering a same problem with `pwntools==4.6.0`.
I've run below script with and without pwndbg, inside tmux.
Tested on `Ubuntu 20.04.1 LTS`

```python
#!/usr/bin/env python3

from pwn import *

context(log_level='debug', arch='amd64', aslr=False, terminal='tmux split -h'.split())
p = process("./prob")
gdb.attach(p)
p.interactive()
```

When I inspect this case, finally I found that PR #1922 corrects this case.
PR #1261 changes logic about running new process in `run_in_new_terminal` which introduces a bug issue #1874
The patch for it is PR #1902 and finally it gets into infinite loop while running on tmux.
However, since `4.8.0` where PR #1922 affects is currently on `dev` branch, it is not applied into `stable` pwntools module.

**Comment by Reinose** [comment]
I forgot to mention @Arusekk .
Could you check it once again?

**Comment by Arusekk** [comment]
Yes, you are correct, the fix has not yet made it to the stable branch; pwntools has been short on manpower for quite a long time now, but we should cut a release cycle soonish
