### ISSUE TITLE
Compatibility with gdb Python API

### ISSUE THREAD

**Issue by MarcoBalossini** [Gallopsled/pwntools#2021]
Using gdb module for python I launch the python file as: `gdb -x test.py`, but trying to import pwntools I get the following exception:
```
Traceback (most recent call last):

  File "test.py", line 1, in <module>
    from pwn import *
  File "/home/balo/.local/lib/python3.10/site-packages/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/home/balo/.local/lib/python3.10/site-packages/pwn/toplevel.py", line 22, in <module>
    import pwnlib
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/__init__.py", line 41, in <module>
    from . import args
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/args.py", line 60, in <module>
    from pwnlib import term
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/term/__init__.py", line 6, in <module>
    from pwnlib.term import completer
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/term/completer.py", line 7, in <module>
    from pwnlib.term import readline
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/term/readline.py", line 12, in <module>
    from pwnlib.term import text
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/term/text.py", line 127, in <module>
    sys.modules[__name__] = Module()
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/term/text.py", line 44, in __init__
    self._reset = termcap.get('reset')
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/term/unix_termcap.py", line 25, in get
    init()
  File "/home/balo/.local/lib/python3.10/site-packages/pwnlib/term/unix_termcap.py", line 59, in init
    curses.setupterm()
TypeError: argument must be an int, or have a fileno() method.
```

I would say that the error is caused only by the starter process (gdb), since I tried with `test.py` like:
```python
from pwn import *
```

**Comment by estarriol43** [comment]
I encountered this  problem as well.

**Comment by teeberg** [comment]
Looking through the code, setting the environment variable `export PWNLIB_NOTERM=1` seems to help.

**Comment by Blizire** [comment]
> Looking through the code, setting the environment variable `export PWNLIB_NOTERM=1` seems to help.

This is still a problem as of 2025 APR. I do not think the answer should be setting up an environment variable that will pollute our global namespace or supplying work arounds with .env files and what not. Would it be worth looking into just detecting if the pwntool modules are being imported by GDB?

As for now my work around to make the pwnlib scripts as portable as possible without any external dependencies or files is setting the environment variable in python before the gdb module import.

```python
import os
os.environ['PWNLIB_NOTERM'] = '1'

import gdb # type: ignore
from pwnlib.util.cyclic import cyclic

pattern = cyclic()

print(pattern)
```
