### ISSUE TITLE
4.7.0: sphinx documentation uses outdated `sphinxcontrib.napoleon`

### ISSUE THREAD

**Issue by kloczek** [Gallopsled/pwntools#2052]
Looks like docs/source/conf.py still uses outdated `sphinxcontrib.napoleon`.
Taht module should be replaced by `sphinx.ext.napoleon`.
I've tested use below patch
```patch
--- a/docs/source/conf.py~      2022-04-08 14:17:56.000000000 +0000
+++ b/docs/source/conf.py       2022-04-08 14:22:46.889537655 +0000
@@ -43,7 +43,7 @@
     'sphinx.ext.todo',
     'sphinx.ext.intersphinx',
     'sphinxcontrib.autoprogram',
-    'sphinxcontrib.napoleon'
+    'sphinx.ext.napoleon'
 ]

 # Disable "info" logging directly to stdout by Sphinx
```
and looks like it is not only change which needs to be done to be able use with latest sphinx.
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.5.0
Filtering Sphinx handler <StreamHandler <stderr> (WARNING)>
Filtering Sphinx handler <StreamHandler <stdout> (NOTSET)>
fatal: not a git repository (or any parent up to mount point /home/tkloczko)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /home/tkloczko)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
making output directory... done
[autosummary] generating autosummary for: about.rst, adb.rst, args.rst, asm.rst, atexception.rst, atexit.rst, commandline.rst, config.rst, constants.rst, context.rst, ..., util/hashes.rst, util/iters.rst, util/lists.rst, util/misc.rst, util/net.rst, util/packing.rst, util/proc.rst, util/safeeval.rst, util/sh_string.rst, util/web.rst
Failed to import pwnlib.rop.srop.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'rop'
Failed to import pwnlib.fmtstr.
Possible hints:
* AttributeError: module 'pwnlib' has no attribute 'fmtstr'
* ModuleNotFoundError: No module named 'sortedcontainers'
Failed to import pwnlib.elf.corefile.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'elf'
Failed to import pwnlib.elf.config.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'elf'
Failed to import pwnlib.rop.ret2dlresolve.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'rop'
Failed to import pwnlib.libcdb.
Possible hints:
* AttributeError: module 'pwnlib' has no attribute 'libcdb'
* ModuleNotFoundError: No module named 'elftools'
Failed to import pwnlib.util.proc.
Possible hints:
* ModuleNotFoundError: No module named 'psutil'
* AttributeError: module 'pwnlib.util' has no attribute 'proc'
Failed to import pwnlib.adb.adb.
Possible hints:
* AttributeError: module 'pwnlib' has no attribute 'adb'
* ModuleNotFoundError: No module named 'psutil'
Failed to import pwnlib.adb.protocol.
Possible hints:
* AttributeError: module 'pwnlib' has no attribute 'adb'
* ModuleNotFoundError: No module named 'psutil'
Failed to import pwnlib.elf.elf.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'elf'
Failed to import pwnlib.rop.rop.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'rop'
Failed to import pwnlib.runner.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'runner'
Failed to import pwnlib.elf.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'elf'
Failed to import pwnlib.gdb.
Possible hints:
* ModuleNotFoundError: No module named 'psutil'
* AttributeError: module 'pwnlib' has no attribute 'gdb'
Failed to import pwnlib.dynelf.
Possible hints:
* ModuleNotFoundError: No module named 'elftools'
* AttributeError: module 'pwnlib' has no attribute 'dynelf'
loading intersphinx inventory from https://docs.python.org/3.8/objects.inv...
loading intersphinx inventory from https://paramiko-docs.readthedocs.org/en/2.1/objects.inv...
intersphinx inventory has moved: https://paramiko-docs.readthedocs.org/en/2.1/objects.inv -> https://docs.paramiko.org/en/2.1/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 75 added, 0 changed, 0 removed
WARNING: autodoc: failed to import module 'adb.adb' from module 'pwnlib'; the following exception was raised:
No module named 'psutil'
WARNING: autodoc: failed to import module 'adb.protocol' from module 'pwnlib'; the following exception was raised:
No module named 'psutil'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/pwntools-4.7.0/pwn/toplevel.py", line 19, in <module>
    import colored_traceback
ModuleNotFoundError: No module named 'colored_traceback'
The full traceback has been saved in /tmp/sphinx-err-6o3rcfvz.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@devel-g2v SOURCES]$ cat /tmp/sphinx-err-6o3rcfvz.log
# Sphinx version: 4.5.0
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:
#   updating environment:
#   [new config]
#   75 added, 0 changed, 0 removed
#   reading sources... [  1%] about
#   reading sources... [  2%] adb
#   reading sources... [  4%] args
#   reading sources... [  5%] asm
#   reading sources... [  6%] atexception
#   reading sources... [  8%] atexit
#   reading sources... [  9%] commandline
# Loaded extensions:
#   sphinx.ext.mathjax (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   pwnlib.internal.dochelper (unknown version) from /home/tkloczko/rpmbuild/BUILD/pwntools-4.7.0/pwnlib/internal/dochelper.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.doctest (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.linkcode (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/linkcode.py
#   sphinx.ext.autosummary (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.coverage (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/coverage.py
#   sphinx.ext.todo (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/todo.py
#   sphinx.ext.intersphinx (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinxcontrib.autoprogram (unknown version) from /usr/lib/python3.8/site-packages/sphinxcontrib/autoprogram.py
#   sphinx.ext.napoleon (4.5.0) from /usr/lib/python3.8/site-packages/sphinx/ext/napoleon/__init__.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/setup_command.py", line 167, in run
    app.build(force_all=self.all_files)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 330, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 283, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 300, in build
    updated_docnames = set(self.read())
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 407, in read
    self._read_serial(docnames)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 428, in _read_serial
    self.read_doc(docname)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 468, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 181, in read_doc
    pub.publish()
  File "/usr/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/lib/python3.8/site-packages/sphinx/io.py", line 101, in read
    self.parse()
  File "/usr/lib/python3.8/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/usr/lib/python3.8/site-packages/sphinx/parsers.py", line 89, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2369, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 318, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "/usr/lib/python3.8/site-packages/docutils/statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/autoprogram.py", line 258, in run
    for line in self.make_rst():
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/autoprogram.py", line 186, in make_rst
    parser = import_object(import_name or "__undefined__")
  File "/usr/lib/python3.8/site-packages/sphinxcontrib/autoprogram.py", line 139, in import_object
    mod = __import__(module_name)
  File "/home/tkloczko/rpmbuild/BUILD/pwntools-4.7.0/pwnlib/commandline/main.py", line 5, in <module>
    from pwnlib.commandline import asm
  File "/home/tkloczko/rpmbuild/BUILD/pwntools-4.7.0/pwnlib/commandline/asm.py", line 11, in <module>
    from pwn import *
  File "/home/tkloczko/rpmbuild/BUILD/pwntools-4.7.0/pwn/__init__.py", line 4, in <module>
    from pwn.toplevel import *
  File "/home/tkloczko/rpmbuild/BUILD/pwntools-4.7.0/pwn/toplevel.py", line 19, in <module>
    import colored_traceback
ModuleNotFoundError: No module named 'colored_traceback'
```

**Comment by Arusekk** [comment]
Please note that because we still support py2, we need to use an ancient sphinx version. Have you checked whether that version supports the change?

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by kloczek** [comment]
Python 2.x is already +2 years EOLed.
If you really want to prowide 2.x support IMO it can be done by create branch and maintain necessary 2.x updates on that branch. This would allow keep mester branch clean.

**Comment by Arusekk** [comment]
Well, I guess so, but maybe not with our current understaffed development.

-- 
Wysłane z mojego urządzenia Sailfish

**Comment by kloczek** [comment]
> Well, I guess so, but maybe not with our current understaffed development.

Actually branching shoul it make easies and cheaper (from point of view of man/hour costs) than mainttaining everything on master. With removed all 2.x stuff on master it will be easier to simpler to maintain. The same on 2.x branch you can add any change without care about python 3.x.

**Comment by gogo2464** [comment]
Sphinx must be updated anyway because it uses a deprecated library that blocks travis cicd. We could use 4.0.0 that seems to support python2. See [my own PR](https://github.com/Gallopsled/pwntools/pull/2053).

**Comment by kloczek** [comment]
> Sphinx must be updated anyway because it uses a deprecated library that blocks travis cicd. We could use 4.0.0 that seems to support python2. See https://github.com/Gallopsled/pwntools/pull/2053.

If it is abput python 2.x support I would recommend to branch repo where such support would be maintained. This would allow keep clean 2.x supporto on master.
Nevertheless pythin 2.x already is two years EOSed ..

**Comment by gogo2464** [comment]
The requirements of python2 and python3 just need to has a diferent version of sphinx. It works on my lastly mentionned PR.

Anyway, maybe we should even might drop support for python2. It has alway has been a bad pratice. Even for pwntools users. Of course they will not like. If I owned pwntools I would have chnaged that but I am not the leader then I continue to maintain it.

**Comment by gogo2464** [comment]
And I do not want of another branch. It will be even harder to maintain.

**Comment by kloczek** [comment]
I'm 100% sure that trying maintain python 2.x and 3.x code compliance in single tree takes more time than keeping clean 2.x branch and 3.x on master.

**Comment by Arusekk** [comment]
Actually, this whole discussion was pointless, since fortunately this ancient sphinx version *does have* a bundled napoleon. I simply had no time to check it before.
