### ISSUE TITLE
Errors during generic use

### ISSUE THREAD

**Issue by init5-SF** [Gallopsled/pwntools#2107]
hello, i am using the below code on Ubuntu 64 bit + 64bit vuln app

```
from pwn import *

elf = ELF("./vuln")

p = process("./vuln")
p.sendline(cyclic(200, n=8))
p.wait()

core = p.corefile

print cyclic_find(core.read(core.rsp, 8), n=8)
```

I am getting the below errors:

```
[*] '/home/dev/Desktop/vuln'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX disabled
    PIE:      No PIE (0x400000)
    RWX:      Has RWX segments
[+] Starting local process './vuln': pid 7220
[*] Process './vuln' stopped with exit code 0 (pid 7220)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/tubes/process.py", line 700, in send_raw
    self.proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dev/Desktop/./exp.py", line 15, in <module>
    p.sendline(cyclic(200, n=8))
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/tubes/tube.py", line 798, in sendline
    self.send(line + self.newline)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/tubes/tube.py", line 777, in send
    self.send_raw(data)
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/tubes/process.py", line 702, in send_raw
    raise EOFError
EOFError
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/pwnlib/tubes/process.py", line 746, in close
    fd.close()
BrokenPipeError: [Errno 32] Broken pipe
```

Any suggestions what could be wrong?

thanks

**Comment by caprinux** [comment]
it seems like your program exits without taking an input. if you are still facing problems, could you share the binary so we can take a look?

**Comment by init5-SF** [comment]
Sure, here you go, thats the source
compiled with -no-pie -fno-stack-protector -z execstack -D_FORTIFY_SOURCE=0
```
#include<stdio.h>
#include<string.h>

void vuln_func();

int main(int argc, char *argv[])
{
	printf("Hey there\n");
	vuln_func();
}

void vuln_func()
{
	char buffer[256];
	gets(buffer);
}

```

**Comment by peace-maker** [comment]
When testing your example program now I get a nicer error say the corefile wasn't found. Your buffer is 256 bytes and your cyclic pattern only 200, so the program doesn't crash.
```
$ python vuln.py
[*] '/tmp/bla/vuln'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX unknown - GNU_STACK missing
    PIE:      No PIE (0x400000)
    Stack:    Executable
    RWX:      Has RWX segments
[+] Starting local process './vuln': pid 6255
[*] Process './vuln' stopped with exit code 0 (pid 6255)
[ERROR] Could not find core file for pid 6255
Traceback (most recent call last):
  File "vuln.py", line 9, in <module>
    core = p.corefile
  File "/home/peace/dev/pwntools/pwnlib/tubes/process.py", line 928, in corefile
    self.error("Could not find core file for pid %i" % self.pid)
  File "/home/peace/dev/pwntools/pwnlib/log.py", line 439, in error
    raise PwnlibException(message % args)
pwnlib.exception.PwnlibException: Could not find core file for pid 6255
```

Changing the cyclic pattern to 300 bytes works as expected
```
$ python vuln.py
[*] '/tmp/bla/vuln'
    Arch:     amd64-64-little
    RELRO:    Partial RELRO
    Stack:    No canary found
    NX:       NX unknown - GNU_STACK missing
    PIE:      No PIE (0x400000)
    Stack:    Executable
    RWX:      Has RWX segments
[+] Starting local process './vuln': pid 6269
[*] Process './vuln' stopped with exit code -11 (SIGSEGV) (pid 6269)
[+] Parsing corefile...: Done                                                                                                 [*] '/tmp/bla/core.6269'
    Arch:      amd64-64-little
    RIP:       0x4011ab
    RSP:       0x7ffcdff64d58
    Exe:       '/tmp/bla/vuln' (0x400000)
    Fault:     0x6261616161616169
264
```

Are you still able to trigger the errors? The relevant changes seem to be https://github.com/Gallopsled/pwntools/commit/fa08f5a7bf41246a39fae81160ba98a386ed5727 and https://github.com/Gallopsled/pwntools/pull/2039

**Comment by peace-maker** [comment]
I assume this was solved. Please reopen if you still enounter this.
