### ISSUE TITLE
Failed to invoke the asm directive

### ISSUE THREAD

**Issue by NightGlowww** [Gallopsled/pwntools#2171]
My computer system is macOS, python version 3.11. When I used it, the following problem occurred. Hoping for a little help :D
```
Python 3.11.2 (main, Feb 16 2023, 03:07:35) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import pwn
>>> pwn.asm("xor eax,eax")
[!] Your binutils is clang-based and may not work!
    Try installing with: https://docs.pwntools.com/en/stable/install/binutils.html
    Reported version: 'Apple clang version 14.0.0 (clang-1400.0.29.202)\nTarget: x86_64-apple-darwin22.3.0\nThread model: posix\nInstalledDir: /Library/Developer/CommandLineTools/usr/bin'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.11/site-packages/pwnlib/context/__init__.py", line 1578, in setter
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pwnlib/asm.py", line 683, in asm
    linker    = _linker()
                ^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pwnlib/asm.py", line 273, in _linker
    ld, _ = which_binutils('ld', check_version=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pwnlib/context/__init__.py", line 1578, in setter
    return function(*a, **kw)
           ^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pwnlib/asm.py", line 224, in which_binutils
    ver = check_binutils_version(res)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pwnlib/asm.py", line 143, in check_binutils_version
    result = subprocess.check_output([util, '--version','/dev/null'],
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/ld', '--version', '/dev/null']' returned non-zero exit status 1.
>>>
```

**Comment by Arusekk** [comment]
Just as it says:

> ```
> [!] Your binutils is clang-based and may not work!
>     Try installing with: https://docs.pwntools.com/en/stable/install/binutils.html
>     Reported version: 'Apple clang version 14.0.0 (clang-1400.0.29.202)\nTarget: x86_64-apple-darwin22.3.0\nThread model: posix\nInstalledDir: /Library/Developer/CommandLineTools/usr/bin'
> ```

There is a draft PR #2161 that may fix the default behavior in the future, but for now, use https://docs.pwntools.com/en/stable/install/binutils.html
