### ISSUE TITLE
pwntools 4.10.0beta0 might break `conda list`/`mamba list`

### ISSUE THREAD

**Issue by lebr0nli** [Gallopsled/pwntools#2183]
After I installed pwntools 4.10.0beta0 in a conda env, pwntools will break `conda list`/`mamba list`:
```
('/path/to/mambaforge/envs/work/lib/python3.10/site-packages/pwntools-4.10.0b0.dist-info', 'pwntools-doc/CHANGELOG.md', 'SHA256=6ouCcHs0s4F33CELcHvIeVo7-WhnIkETMwtYs4wQO10')

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/exceptions.py", line 1124, in __call__
        return func(*args, **kwargs)
      File "/path/to/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 941, in exception_converter
        raise e
      File "/path/to/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 934, in exception_converter
        exit_code = _wrapped_main(*args, **kwargs)
      File "/path/to/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 892, in _wrapped_main
        result = do_call(parsed_args, p)
      File "/path/to/mambaforge/lib/python3.10/site-packages/mamba/mamba.py", line 750, in do_call
        exit_code = getattr(module, func_name)(args, parser)
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/cli/main_list.py", line 137, in execute
        exitcode = print_packages(prefix, regex, format, piplist=args.pip,
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/cli/main_list.py", line 76, in print_packages
        exitcode, output = list_packages(prefix, regex, format=format,
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/cli/main_list.py", line 42, in list_packages
        installed = sorted(PrefixData(prefix, pip_interop_enabled=True).iter_records(),
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/core/prefix_data.py", line 136, in iter_records
        return iter(self._prefix_records.values())
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/core/prefix_data.py", line 165, in _prefix_records
        return self.__prefix_records or self.load() or self.__prefix_records
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/common/io.py", line 84, in decorated
        return f(*args, **kwds)
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/core/prefix_data.py", line 75, in load
        self._load_site_packages()
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/core/prefix_data.py", line 282, in _load_site_packages
        python_record = read_python_record(self.prefix_path, af, python_pkg_record.version)
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/gateways/disk/read.py", line 245, in read_python_record
        paths_tups = pydist.get_paths()
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/common/pkg_formats/python.py", line 265, in get_paths
        records = process_csv_row(record_reader)
      File "/path/to/mambaforge/lib/python3.10/site-packages/conda/common/pkg_formats/python.py", line 248, in process_csv_row
        assert checksum.startswith('sha256='), (self._metadata_dir_full_path,
    AssertionError: ('/path/to/mambaforge/envs/work/lib/python3.10/site-packages/pwntools-4.10.0b0.dist-info', 'pwntools-doc/CHANGELOG.md', 'SHA256=6ouCcHs0s4F33CELcHvIeVo7-WhnIkETMwtYs4wQO10')
```

Then I need to manually replace every `SHA256` to `sha256` in `/path/to/site-packages/pwntools-4.10.0b0.dist-info/RECORD` to make the commands works again.

Is it possible to let pwntools use `sha256` instead of `SHA256` when installing?

**Comment by Arusekk** [comment]
I have no experience with (ana)conda nor mamba, can you try to trace the bug a little further? I'm pretty sure this is the fault of something like a `setuptools` version update.

**Comment by lebr0nli** [comment]
> I'm pretty sure this is the fault of something like a setuptools version update.

Ahh, yeah, you're right, this is related to setuptools.
After I invested into this problem a little bit further, I think this issue is probably caused by the package that pwntools uploaded to pypi. (I'm not sure what's the setuptools version that pwntools used when it generated the package tho.)

I tried `python setup.py sdist bdist_wheel --universal` and `pip install dist/pwntools-4.10.0b0-py2.py3-none-any.whl` locally with the latest `setuptools` and `wheel`, this issue is gone. (I tested with `setuptools==67.7.2` and `wheel==0.40.0`.)

The `RECORD` file in `pwntools-4.10.0b0-py2.py3-none-any.whl` that I generated locally:
```
pwn/__init__.py,sha256=tHM96EGlpEeeExFeonksuPuNfk1dzxp8tklY3FXJqh0,576
pwn/toplevel.py,sha256=yE74LosXD2xq0VhCxNbVGLMAS7WqwQTHsJwiclO8DuU,2743
pwnlib/__init__.py,sha256=qlM3ofYcD4VyYOySD9H4EuCb4Gtj-LcADr3Lyavkauk,570
pwnlib/abi.py,sha256=az0l7w4lYyvGrvHlv3RyDjP7XLMrQ9tSr3MDRQHrg9o,7507
pwnlib/args.py,sha256=lH8zEQ_1I5su4qjaGLWQVbUNtJZVchN00YxvLlkmiQw,5551
pwnlib/asm.py,sha256=gYUQWJBUiWpdoVlLPU-e1bAcBVFo5dTPmf7zRu4U61c,27825
pwnlib/atexception.py,sha256=3Gmi002hwMXhP70TxLyai_RUYPaeW9pbBeflCWUrjFo,2959
pwnlib/atexit.py,sha256=eXWUPw5B3c7qT3hkqLMTSig0n7wzYUCGdMyrz9H0tR4,3010
pwnlib/config.py,sha256=huJ4RduplrmAmVeZnr9el3XgFaqFbSUn7j9abT3_8_c,2127
pwnlib/device.py,sha256=jE5m0k1MNYTk2xz8cnkd-MttU6q-m2G_hxEg3zV14O0,318
...
```

The `RECORD` file in [the wheel file I downloaded from pypi](https://pypi.org/project/pwntools/4.10.0b0/#files):
```
pwn/__init__.py,SHA256=tHM96EGlpEeeExFeonksuPuNfk1dzxp8tklY3FXJqh0,576
pwn/toplevel.py,SHA256=yE74LosXD2xq0VhCxNbVGLMAS7WqwQTHsJwiclO8DuU,2743
pwnlib/__init__.py,SHA256=qlM3ofYcD4VyYOySD9H4EuCb4Gtj-LcADr3Lyavkauk,570
pwnlib/abi.py,SHA256=az0l7w4lYyvGrvHlv3RyDjP7XLMrQ9tSr3MDRQHrg9o,7507
pwnlib/args.py,SHA256=lH8zEQ_1I5su4qjaGLWQVbUNtJZVchN00YxvLlkmiQw,5551
pwnlib/asm.py,SHA256=gYUQWJBUiWpdoVlLPU-e1bAcBVFo5dTPmf7zRu4U61c,27825
pwnlib/atexception.py,SHA256=3Gmi002hwMXhP70TxLyai_RUYPaeW9pbBeflCWUrjFo,2959
pwnlib/atexit.py,SHA256=eXWUPw5B3c7qT3hkqLMTSig0n7wzYUCGdMyrz9H0tR4,3010
pwnlib/config.py,SHA256=huJ4RduplrmAmVeZnr9el3XgFaqFbSUn7j9abT3_8_c,2127
pwnlib/device.py,SHA256=jE5m0k1MNYTk2xz8cnkd-MttU6q-m2G_hxEg3zV14O0,318
...
```
