### ISSUE TITLE
DynELF don't working..

### ISSUE THREAD

**Issue by HQ1995** [Gallopsled/pwntools#245]
I have installed the latest version on github,but when I open an elf use DynELF('./elf',leaker),It doesn't working...

```
Traceback (most recent call last):
  File "mario.py", line 26, in <module>
    elf=DynELF('./pwnme',leak_write)
  File "/usr/local/lib/python2.7/dist-packages/pwntools/pwnlib/dynelf.py", line 112, in __init__
    self.libbase = self._find_base(pointer or elf.address)
  File "/usr/local/lib/python2.7/dist-packages/pwntools/pwnlib/dynelf.py", line 196, in _find_base
    ptr &= page_mask
TypeError: unsupported operand type(s) for &=: 'MemLeak' and 'int'
```

**Comment by bjchan9an** [comment]
DynELF() 's first param is a function which can leak anywhere 's 4 bytes,for example:
DynELF(leak,elf='./')
