### ISSUE TITLE
Importing shellcraft submodules doesn't work

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#317]
```
$ python
>>> import pwnlib.shellcraft.arm
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named arm
```

**Comment by zachriggle** [comment]
Currently the only issue for this is that it throws some warnings when generating documentation.

Looks like the issue is related to the deferred loading.

```py
>>> import pwnlib
>>> import pwnlib.shellcraft.thumb
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named thumb
>>> pwnlib.shellcraft.thumb                                                                                                                                 
<module 'pwnlib.shellcraft.thumb' from '/usr/local/google/home/riggle/pwntools/pwnlib/shellcraft/__init__.pyc'>
>>> import pwnlib.shellcraft.thumb
```

**Comment by IdolfHatler** [comment]
The problem is that we have lazy loading of shellcraft for performance reason. This lazy loading breaks with pythons assumptions about how modules are loaded. I created a custom import-loader to fix it.
