### ISSUE TITLE
cyclic broken

### ISSUE THREAD

**Issue by IdolfHatler** [Gallopsled/pwntools#387]
$ cyclic -o 0x61616161
Traceback (most recent call last):
  File "/usr/local/bin/cyclic", line 9, in <module>
    load_entry_point('pwntools==2.2', 'console_scripts', 'cyclic')()
  File "/home/freaken/git/pwntools/pwnlib/commandline/cyclic.py", line 49, in main
    pat = packing.pack(int(pat[2:], 16), subsize*8, 'little', 'unsigned')
  File "/home/freaken/git/pwntools/pwnlib/util/packing.py", line 94, in pack
    raise ValueError("pack(): sign must be either True or False (got %r)" % sign)
ValueError: pack(): sign must be either True or False (got 'unsigned')

**Comment by IdolfHatler** [comment]
Pinging #338.

**Comment by zachriggle** [comment]
Check out my comment on there.  Also, I have opened a PR to fix this (#387) issue.
