### ISSUE TITLE
shellcraft i386.mov and amd64.mov broken for some values

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#467]
It appears that this occurs because of some expectations about there being an `ah` equivalent for `ebp`, `esp`, `edi`, and `esi`.

```
$ shellcraft i386.mov edi 0x0300
Traceback (most recent call last):
  File "/home/user/.pyenv/versions/2.7.9/bin/shellcraft", line 9, in <module>
    load_entry_point('pwntools==2.2.0', 'console_scripts', 'shellcraft')()
  File "/home/user/pwntools/pwnlib/commandline/shellcraft.py", line 239, in main
    code = func(*args.args)
  File "<string>", line 6, in mov
  File "/home/user/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/home/user/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/home/user/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/home/user/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/home/user/.pwntools-cache/mako/i386/mov.asm.py", line 138, in render_body
    elif srcu == srcu & 0xff00 and okay(srcp[1]) and sizes[smaller[dest][-2]] == 8:
IndexError: list index out of range
````

**Comment by Idolf** [comment]
This was fixed by #636.
