### ISSUE TITLE
shellcraft.i386.push is broken

### ISSUE THREAD

**Issue by zachriggle** [Gallopsled/pwntools#522]
```
$ shellcraft i386.linux.push 0xdeadbeef -fasm
```

```
Traceback (most recent call last):
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/bin/shellcraft", line 9, in <module>
    load_entry_point('binjitsu==2.2.1', 'console_scripts', 'shellcraft')()
  File "/usr/local/google/home/riggle/binjitsu/pwnlib/commandline/shellcraft.py", line 185, in main
    code = func(*args.args)
  File "<string>", line 6, in push
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/usr/local/google/home/riggle/.binjitsu-cache/mako/i386/linux/push.asm.py", line 33, in render_body
    __M_writer(unicode(i386.push(value)))
  File "<string>", line 6, in push
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/template.py", line 443, in render
    return runtime._render(self, self.callable_, args, data)
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 803, in _render
    **_kwargs_for_callable(callable_, data))
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 835, in _render_context
    _exec_template(inherit, lclcontext, args=args, kwargs=kwargs)
  File "/usr/local/google/home/riggle/.pyenv/versions/2.7.9/lib/python2.7/site-packages/mako/runtime.py", line 860, in _exec_template
    callable_(context, *args, **kwargs)
  File "/usr/local/google/home/riggle/.binjitsu-cache/mako/i386/push.asm.py", line 63, in render_body
    __M_writer(unicode(re.sub(r'^\s*/.*\n', '', i386.pushstr(packing.pack(value, 32, 'little', True), False), 1)))
  File "/usr/local/google/home/riggle/binjitsu/pwnlib/util/packing.py", line 128, in pack
    raise ValueError("pack(): number does not fit within word_size")
ValueError: pack(): number does not fit within word_size
```

**Comment by zachriggle** [comment]
@Idolf: It looks like you wrote the code that broke this in 521e675e.

Specifically, this change:

```diff
-${i386.pushstr(packing.pack(value, 32), False)}
+${i386.pushstr(packing.pack(value, 32, 'little', True), False)}
```

Why expressly override the endianness and signed-ness?  Changing this back makes it work, and the output appears to be correct.

```
$ shellcraft  i386.linux.push 0xdeadbeef  | disasm
   0:   68 ef be ad de          push   0xdeadbeef
$ shellcraft  i386.linux.push 0x01adbeef  | disasm
   0:   68 ef be ad 01          push   0x1adbeef
$ shellcraft  i386.linux.push 0x00adbeef  | disasm
   0:   68 01 01 01 01          push   0x1010101
   5:   81 34 24 ee bf ac 01    xor    DWORD PTR [esp],0x1acbfee
$ shellcraft  i386.linux.push 0xffffffff  | disasm
   0:   6a ff                   push   0xffffffff
```

As a side-note, we should figure out a better way to strip comments than:

```py
${re.sub(r'^\s*/.*\n', '', ...)}
```
