### ISSUE TITLE
Building rop chain for amd64 failed

### ISSUE THREAD

**Issue by BrieflyX** [Gallopsled/pwntools#585]
I try to build an rop chain on an amd64 elf file but got:

```
[ERROR] Cannot build rop for architecture 'amd64'
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pwntools-2.2.0-py2.7.egg/pwnlib/rop.py", line 265, in dump
    rop = self.build(self.base or 0)
  File "/usr/lib/python2.7/site-packages/pwntools-2.2.0-py2.7.egg/pwnlib/rop.py", line 208, in build
    log.error("Cannot build rop for architecture %r" % self.elfs[0].get_machine_arch())
  File "/usr/lib/python2.7/site-packages/pwntools-2.2.0-py2.7.egg/pwnlib/log.py", line 369, in error
    raise PwnlibException(message % args)
pwnlib.exception.PwnlibException: Cannot build rop for architecture 'amd64'
```

Notice that there is a '_build_i386' function in rop but no '_build_amd64', is it not implemented yet or a program bug?

**Comment by zachriggle** [comment]
amd64 is not supported, as the error message states.
