### ISSUE TITLE
Cyclic 'unsigned' error

### ISSUE THREAD

**Issue by dtouch3d** [Gallopsled/pwntools#587]
I installed pwntools 2.2 from pip, run

    $ cyclic 1024
    $ cyclic -l 0x63616172

and got a 

````
Traceback (most recent call last):
  File "/usr/bin/cyclic", line 9, in <module>
    load_entry_point('pwntools==2.2', 'console_scripts', 'cyclic')()
  File "/usr/lib/python2.7/site-packages/pwnlib/commandline/cyclic.py", line 49, in main
    pat = packing.pack(int(pat[2:], 16), subsize*8, 'little', 'unsigned')
  File "/usr/lib/python2.7/site-packages/pwnlib/util/packing.py", line 94, in pack
    raise ValueError("pack(): sign must be either True or False (got %r)" % sign)
ValueError: pack(): sign must be either True or False (got 'unsigned')
````

Seems like the pack function takes the sign arg as True or False but other functions take 'signed' or 'unsigned'. The change was easy.

In file pwnlib/util/packing.py:

````python
    with context.local(**kwargs):                                                                                                                                                
        # Lookup in context if not found                                                                                                                                         
        word_size  = word_size  or context.word_size                                                                                                                             
        endianness = endianness or context.endianness                                                                                                                            
        sign       = sign       or context.sign
        
        # new line                                                                                                                                     
        sign = (sign == 'signed')                                                                                                                              
````  
After the change cyclic returns the correct offset. This seems so basic though that I am almost sure something else is amiss. I use Arch Linux. Thanks!

**Comment by zachriggle** [comment]
This is fixed in Binjitsu, but not in Gallopsled/pwntools/master.

**Comment by Idolf** [comment]
It is after #636.
