### ISSUE TITLE
argparse listed in requires.txt causes command line tools to fail

### ISSUE THREAD

**Issue by lantw44** [Gallopsled/pwntools#598]
Python 2.7 already includes argparse in its standard library, so users don't have to install it before using. `import argparse` works fine, but listing it in requires.txt causes error because no egg info is available.

```
$ python2
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import argparse
>>> argparse
<module 'argparse' from '/usr/lib64/python2.7/argparse.pyc'>
>>> 
$ asm --help
Traceback (most recent call last):
  File "/usr/bin/asm", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3084, in <module>
    @_call_aside
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3070, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 3097, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 651, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 952, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 839, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'argparse' distribution was not found and is required by pwntools
```

I know `pip install` pulls in another copy of argparse automatically to resolve this issue, but it is not good to install the same library twice and I use setup.py instead of pip. Removing argparse from requires.txt fixes the problem. Can we make the argparse requirement optional?

**Comment by zachriggle** [comment]
Don't use setup.py directly, use pip. If you'd like a local install, use"
pip -Ue ."

**Comment by lantw44** [comment]
`pip install` installs an extra copy of argparse. It can be used to workaround the problem, but it is better to not to require argparse on python >= 2.7.

```
$ pip install --user -Ue .
You are using pip version 7.1.0, however version 8.1.0 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Obtaining file:///path/to/pwntools
Collecting paramiko>=1.15.2 (from pwntools==2.2.0)
  Downloading paramiko-1.16.0-py2.py3-none-any.whl (169kB)
    100% |████████████████████████████████| 172kB 1.7MB/s 
Collecting argparse (from pwntools==2.2.0)
  Downloading argparse-1.4.0-py2.py3-none-any.whl
...
```

**Comment by zachriggle** [comment]
Well it looks like it didn't break anything to remove it, and if it's causing problems for other folks, may as well remove it.
