### ISSUE TITLE
curses error when I import pwn

### ISSUE THREAD

**Issue by parksjin01** [Gallopsled/pwntools#794]
```python
Traceback (most recent call last):
  File "/Users/Knight/PycharmProjects/untitled/gmail.py", line 1, in <module>
    import pwn
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwn/__init__.py", line 2, in <module>
    from .toplevel import *
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwn/toplevel.py", line 20, in <module>
    import pwnlib
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwnlib/__init__.py", line 40, in <module>
    importlib.import_module('.%s' % module, 'pwnlib')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwnlib/args.py", line 10, in <module>
    from . import term
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwnlib/term/__init__.py", line 3, in <module>
    from . import completer
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwnlib/term/completer.py", line 4, in <module>
    from . import readline
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwnlib/term/readline.py", line 4, in <module>
    from . import text
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwnlib/term/text.py", line 115, in <module>
    sys.modules[__name__] = Module()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwnlib/term/text.py", line 26, in __init__
    self.num_colors = termcap.get('colors', default = 8)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pwnlib/term/termcap.py", line 25, in get
    s = curses.tigetstr(cap)
_curses.error: must call (at least) setupterm() first
```

I get this kind of error. I can't get any idea why I get this kind of error. Help me please

**Comment by zachriggle** [comment]
Please provide the information requested by the issue template.

**Comment by parksjin01** [comment]
I can't understand your comment. Can you explain one more time please?
(I'm using latest version of pwntools, I can use pwntools in linux but not in mac)

**Comment by DuckLL** [comment]
OS: macOS 10.12.1
Python: 2.7.12 (install via brew)
IDE: VS Code with Python plugin

When I debugged code, the same error came up too.

**Comment by zachriggle** [comment]
macOS is unsupported.  Anything that *does* work is a happy accident.
