### ISSUE TITLE
ssh() can't connect

### ISSUE THREAD

**Issue by nil0x42** [Gallopsled/pwntools#855]
# context()
system: ArchLinux (4.8.13-1-ARCH)
python: 2.7.13
pwntools: 3.3.4 (pip latest)

# issue
connecting to a wargame-challengs server over ssh fails when using paramiko2

# steps to reproduce
**`$ python2`**
```python
Python 2.7.13 (default, Dec 21 2016, 07:16:46)
[GCC 6.2.1 20160830] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from pwn import *
>>> ssh("esoteric3", "wargame.w3challs.com", 20202, "esoteric3")
[x] Connecting to wargame.w3challs.com on port 20202
[-] Connecting to wargame.w3challs.com on port 20202: Failed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/pwnlib/tubes/ssh.py", line 554, in __init__
    self.client.load_host_keys(known_hosts)
  File "/usr/lib/python2.7/site-packages/paramiko/client.py", line 124, in load_host_keys
    self._host_keys.load(filename)
  File "/usr/lib/python2.7/site-packages/paramiko/hostkeys.py", line 101, in load
    e = HostKeyEntry.from_line(line, lineno)
  File "/usr/lib/python2.7/site-packages/paramiko/hostkeys.py", line 331, in from_line
    key = RSAKey(data=decodebytes(key))
  File "/usr/lib/python2.7/site-packages/paramiko/rsakey.py", line 58, in __init__
    ).public_key(default_backend())
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 349, in public_key
    return backend.load_rsa_public_numbers(self)
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/multibackend.py", line 164, in load_rsa_public_numbers
    return b.load_rsa_public_numbers(numbers)
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/backends/openssl/backend.py", line 459, in load_rsa_public_numbers
    rsa._check_public_key_components(numbers.e, numbers.n)
  File "/usr/lib/python2.7/site-packages/cryptography/hazmat/primitives/asymmetric/rsa.py", line 173, in _check_public_key_components
    raise ValueError("e must be >= 3 and < n.")
ValueError: e must be >= 3 and < n.
```

**Comment by nil0x42** [comment]
NOTE: I saw you only support ubuntu, therefore if you have an idea of problem's origin, it would help me to upgrade BlackArch's pwntools packaging

**Comment by zachriggle** [comment]
It looks like your SSH key or host are misconfigured.

**Comment by zachriggle** [comment]
(Specifically, you have an extremely weak key in your known_hosts file that you should remove.  It looks like Paramiko won't work with that entry. I would recommend seeing if Paramjko works at all on your system.)
