### ISSUE TITLE
ssh.download_file(): Pernission denied

### ISSUE THREAD

**Issue by nil0x42** [Gallopsled/pwntools#858]
# download_file() fails on readable file

```python
>>> s=ssh("esoteric3", "wargame.w3challs.com", 20202, "esoteric3")
>>> s.download_file("tinypwn", "/tmp/test2")
[x] Downloading './tinypwn' to '/tmp/test2'
[-] Downloading './tinypwn' to '/tmp/test2': Failed
Traceback (most recent call last):
  File "<input>", line 1, in <module>
    s.download_file("tinypwn", "/tmp/test2")
  File "/usr/lib/python2.7/site-packages/pwnlib/tubes/ssh.py", line 1327, in download_file
    local_tmp = self._download_to_cache(remote, p)
  File "/usr/lib/python2.7/site-packages/pwnlib/tubes/ssh.py", line 1275, in _download_to_cache
    self._download_raw(remote, local, p)
  File "/usr/lib/python2.7/site-packages/pwnlib/tubes/ssh.py", line 1223, in _download_raw
    self.sftp.get(remote, local, update)
  File "/usr/lib/python2.7/site-packages/paramiko/sftp_client.py", line 721, in get
    size = self.getfo(remotepath, fl, callback)
  File "/usr/lib/python2.7/site-packages/paramiko/sftp_client.py", line 696, in getfo
    with self.open(remotepath, 'rb') as fr:
  File "/usr/lib/python2.7/site-packages/paramiko/sftp_client.py", line 327, in open
    t, msg = self._request(CMD_OPEN, filename, imode, attrblock)
  File "/usr/lib/python2.7/site-packages/paramiko/sftp_client.py", line 730, in _request
    return self._read_response(num)
  File "/usr/lib/python2.7/site-packages/paramiko/sftp_client.py", line 781, in _read_response
    self._convert_status(msg)
  File "/usr/lib/python2.7/site-packages/paramiko/sftp_client.py", line 809, in _convert_status
    raise IOError(errno.EACCES, text)
IOError: [Errno 13] Permission denied
>>> print(s.system("wc -c tinypwn").read())
[x] Opening new channel: 'wc -c tinypwn'
[+] Opening new channel: 'wc -c tinypwn': Done
2098747 tinypwn

>>> print(s.system("ls -lah tinypwn").read())
[x] Opening new channel: 'ls -lah tinypwn'
[+] Opening new channel: 'ls -lah tinypwn': Done
-r-sr-x--- 1 esoteric3_pwned esoteric3 2.1M May  1  2014 tinypwn
```

**Comment by nil0x42** [comment]
okay, after reading the sources, it's due to the fact that pwntools does downloads through sftp and not scp, the openssh's `sftp` client gave the same results.

adding scp capability on pwntools could be nice, for the moment, i'll just do this:
```python
file=s.system("/bin/printf REMOTEFILE").read()
```

**Comment by zachriggle** [comment]
You can disable SFTP on the `ssh` object by setting its `sftp` attribute to `None` per the documentation:

http://docs.pwntools.com/en/dev/tubes/ssh.html#pwnlib.tubes.ssh.ssh.sftp

It looks like at some point we deferred initialization of the `sftp` object via using a property, but a setter was never added.

I added a setter in 2e90d051561a14e6989aca56dbd2dff037cdd804.  In the meantime, you can just set `._sftp` and `_tried_sftp`, and it'll fall back to using shell commands.
