### ISSUE TITLE
WHEN   I  USE ROP（），IT always  WRONG

### ISSUE THREAD

**Issue by letitbezh** [Gallopsled/pwntools#922]
b = ELF('./login')
rop = ROP(b)
when I use this，the ROP always  wrong，log is like this
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/angr/pwntools/pwnlib/rop/rop.py", line 398, in __init__
    import ropgadget
  File "/home/angr/ctfpwn/local/lib/python2.7/site-packages/ropgadget/__init__.py", line 14, in <module>
    import ropgadget.binary
  File "/home/angr/ctfpwn/local/lib/python2.7/site-packages/ropgadget/binary.py", line 13, in <module>
    from ropgadget.loaders.elf       import *
  File "/home/angr/ctfpwn/local/lib/python2.7/site-packages/ropgadget/loaders/__init__.py", line 13, in <module>
    import ropgadget.loaders.elf
  File "/home/angr/ctfpwn/local/lib/python2.7/site-packages/ropgadget/loaders/elf.py", line 13, in <module>
    from capstone   import *
  File "/home/angr/ctfpwn/local/lib/python2.7/site-packages/capstone/__init__.py", line 6, in <module>
    from . import arm, arm64, mips, ppc, sparc, systemz, x86, xcore
ImportError: cannot import name arm
```
what should. I do ?  THANK YOU

**Comment by zachriggle** [comment]
I have no idea, looks like your install is broken.  Try on a clean machine or Docker.

**Comment by letitbezh** [comment]
i use env  ,but it is wrong ... i think   i should try docker

**Comment by zachriggle** [comment]
There is a docker image that you can use pretty easily.  Just `docker pull pwntools/pwntools:stable` (or `:dev` if you prefer).
